[package]
name = "fe-resolver"
version = "0.26.0"
authors = ["The Fe Developers <snakecharmers@ethereum.org>"]
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/ethereum/fe"
description = "Resolver lib for Fe."

[dependencies]
common.workspace = true
smol_str.workspace = true
camino.workspace = true
url.workspace = true
glob.workspace = true
semver.workspace = true
petgraph.workspace = true

indexmap = "2.9"
git2 = "0.19"
dir-test.workspace = true
test-utils.workspace = true
toml = "0.8"
