use crate::{
    analysis::{
        HirAnalysisDb,
        ty::{
            constraint::ConstraintId,
            generated::{GeneratedImplId, GeneratedImplSource},
        },
    },
    hir_def::{IdentId, TopLevelMod},
};

use super::{
    ElaborationCtfeContextId, ElaborationRequestId, RequirementOrigin, generated_impls_for_ingot,
};

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, salsa::Update)]
pub(crate) enum GeneratedTraceFact<'db> {
    RequestedBy(ElaborationRequestId<'db>),
    GeneratedBy(ElaborationCtfeContextId<'db>),
    ConsumesDeriveEvidence(ConstraintId<'db>),
    Source(GeneratedImplSource<'db>),
    ProvidesEvidence(ConstraintId<'db>),
    EmitsMethod {
        name: IdentId<'db>,
    },
    RequiresConstraint {
        constraint: ConstraintId<'db>,
        origin: RequirementOrigin<'db>,
    },
}

impl<'db> GeneratedTraceFact<'db> {
    fn pretty_print(self, db: &'db dyn HirAnalysisDb, generated: GeneratedImplId<'db>) -> String {
        let prefix = generated.trait_inst.pretty_print(db, true);
        match self {
            Self::RequestedBy(request) => {
                format!(
                    "{prefix} requested by {}",
                    request.origin(db).pretty_print()
                )
            }
            Self::GeneratedBy(context) => {
                let provider = context.provider(db).identity(db).pretty_print(db);
                format!("{prefix} generated by {provider}")
            }
            Self::ConsumesDeriveEvidence(constraint) => {
                format!("{prefix} consumes {}", constraint.pretty_print(db))
            }
            Self::Source(source) => format!(
                "{prefix} generated output source {}",
                source.pretty_print(db)
            ),
            Self::ProvidesEvidence(constraint) => {
                format!("{prefix} provides {}", constraint.pretty_print(db))
            }
            Self::EmitsMethod { name } => {
                format!("{prefix} emits method {}", name.data(db))
            }
            Self::RequiresConstraint { constraint, origin } => {
                format!(
                    "{prefix} requires {} {}",
                    constraint.pretty_print(db),
                    origin.pretty_print(db)
                )
            }
        }
    }
}

pub fn generated_impl_summaries_for_top_mod<'db>(
    db: &'db dyn HirAnalysisDb,
    top_mod: TopLevelMod<'db>,
) -> Vec<String> {
    generated_impls_for_ingot(db, top_mod.ingot(db))
        .iter()
        .filter(|generated| generated.context.request(db).target(db).item().top_mod(db) == top_mod)
        .map(|generated| {
            format!(
                "generated {} {} with obligations {}",
                generated.source.pretty_print(db),
                generated.trait_inst.pretty_print(db, true),
                generated.obligations.pretty_print(db),
            )
        })
        .collect()
}

pub fn generated_trace_summaries_for_top_mod<'db>(
    db: &'db dyn HirAnalysisDb,
    top_mod: TopLevelMod<'db>,
) -> Vec<String> {
    generated_impls_for_ingot(db, top_mod.ingot(db))
        .iter()
        .filter(|generated| generated.context.request(db).target(db).item().top_mod(db) == top_mod)
        .flat_map(|&generated| {
            generated_trace_facts(db, generated)
                .into_iter()
                .map(move |fact| fact.pretty_print(db, generated))
        })
        .collect()
}

pub fn generated_requirement_artifact_summaries_for_top_mod<'db>(
    db: &'db dyn HirAnalysisDb,
    top_mod: TopLevelMod<'db>,
) -> Vec<String> {
    generated_impls_for_ingot(db, top_mod.ingot(db))
        .iter()
        .filter(|generated| generated.context.request(db).target(db).item().top_mod(db) == top_mod)
        .flat_map(|&generated| {
            generated
                .requirements
                .list(db)
                .iter()
                .enumerate()
                .map(move |(index, requirement)| {
                    format!(
                        "{} requirement #{} requires {} {}",
                        generated.trait_inst.pretty_print(db, true),
                        index,
                        requirement.constraint.pretty_print(db),
                        requirement.origin.pretty_print(db)
                    )
                })
                .collect::<Vec<_>>()
        })
        .collect()
}

pub fn generated_method_artifact_summaries_for_top_mod<'db>(
    db: &'db dyn HirAnalysisDb,
    top_mod: TopLevelMod<'db>,
) -> Vec<String> {
    generated_impls_for_ingot(db, top_mod.ingot(db))
        .iter()
        .filter(|generated| generated.context.request(db).target(db).item().top_mod(db) == top_mod)
        .flat_map(|&generated| {
            generated
                .methods
                .list(db)
                .iter()
                .enumerate()
                .map(move |(index, method)| {
                    format!(
                        "{} method #{} emits {}",
                        generated.trait_inst.pretty_print(db, true),
                        index,
                        method.name.data(db)
                    )
                })
                .collect::<Vec<_>>()
        })
        .collect()
}

fn generated_trace_facts<'db>(
    db: &'db dyn HirAnalysisDb,
    generated: GeneratedImplId<'db>,
) -> Vec<GeneratedTraceFact<'db>> {
    let mut facts = vec![
        GeneratedTraceFact::RequestedBy(generated.context.request(db)),
        GeneratedTraceFact::GeneratedBy(generated.context),
        GeneratedTraceFact::ConsumesDeriveEvidence(generated.context.derive_evidence(db)),
        GeneratedTraceFact::Source(generated.source),
        GeneratedTraceFact::ProvidesEvidence(ConstraintId::from_trait(db, generated.trait_inst)),
    ];
    facts.extend(generated.requirements.list(db).iter().map(|requirement| {
        GeneratedTraceFact::RequiresConstraint {
            constraint: requirement.constraint,
            origin: requirement.origin,
        }
    }));
    facts.extend(
        generated
            .methods
            .list(db)
            .iter()
            .map(|method| GeneratedTraceFact::EmitsMethod { name: method.name }),
    );
    facts
}
