[workspace]
members = ["crates/*", "crates/language-server/editors/zed"]
resolver = "2"

[profile.dev.package.solc]
opt-level = 3

[profile.dev]
# Speeds up the build. May need to diable for debugging.
debug = 0
