[workspace]
name = "Fe"
version = "0.1.0"
members = [
  { path = "ingots/core", name = "core" },
  { path = "ingots/core_derives", name = "core_derives" },
  { path = "ingots/std", name = "std" },
  { path = "demos/sketches/fmath", name = "fmath" },
  { path = "demos/sketches/plasma", name = "plasma" },
  { path = "demos/sketches/dec", name = "dec" },
  { path = "demos/sketches/gradient", name = "gradient" },
  { path = "demos/sketches/mandelbrot", name = "mandelbrot" },
  { path = "ingots/sparse_clifford", name = "sparse_clifford" },
  { path = "ingots/gaplay", name = "gaplay" },
  { path = "demos/sketches/qcga", name = "qcga" },
  { path = "demos/sketches/cga3d", name = "cga3d" },
  { path = "demos/sketches/desargues", name = "desargues" },
  { path = "demos/sketches/qcga_pencil", name = "qcga_pencil" },
]
