[ingot]
name = "fri_baby_bear"
version = "0.1.0"

[dependencies]
core = { path = "../core" }
fri_structure = { path = "../fri_structure" }
poseidon_baby_bear = { path = "../poseidon_baby_bear" }
precision = "../../demos/sketches/precision"
