[ingot]
name = "mandelbrot_proof_baby_bear"
version = "0.1.0"

[dependencies]
core = "../../../../ingots/core"
mandelbrot_proof_kernel = "../kernel"
poseidon_baby_bear = "../../../../ingots/poseidon_baby_bear"
precision = "../../../sketches/precision"
