crate::define_closed_string_enum! {
    #[derive(Clone, Copy, Debug, PartialEq, Eq, PartialOrd, Ord, Hash)]
    pub enum TypedFactRelationColumnName {
        Id => "id",
        Kind => "kind",
        OwnerKey => "owner_key",
        LocalKey => "local_key",
        From => "from",
        To => "to",
        Origin => "origin",
        SpanKind => "span_kind",
        File => "file",
        StartByte => "start_byte",
        EndByte => "end_byte",
        StartLine => "start_line",
        StartCol => "start_col",
        EndLine => "end_line",
        EndCol => "end_col",
        SourceId => "source_id",
        StableKey => "stable_key",
        Node => "node",
        Dimension => "dimension",
        Name => "name",
        Value => "value",
        Parent => "parent",
        Child => "child",
        Label => "label",
        Order => "order",
        EventKind => "event_kind",
        Source => "source",
        Target => "target",
        Scope => "scope",
        DigestHex => "digest_hex",
    }
}
