[ingot]
name = "mandelbrot_proof_recursive"
version = "0.1.0"

[dependencies]
canonical_words = "../../../../ingots/canonical_words"
core = "../../../../ingots/core"
precision = "../../../sketches/precision"
