[ingot]
name = "mandelbrot_proof_gpu"
version = "0.1.0"

[dependencies]
canonical_words = { path = "../../../ingots/canonical_words" }
core = { path = "../../../ingots/core" }
fmath = { path = "../fmath" }
fri_baby_bear = { path = "../../../ingots/fri_baby_bear" }
mandelbrot_proof_air_core = { path = "../../capstones/mandelbrot-proof/air-core" }
mandelbrot_proof_baby_bear_domains = { path = "../../capstones/mandelbrot-proof/baby-bear-domains" }
mandelbrot_proof_baby_bear_encoding = { path = "../../capstones/mandelbrot-proof/baby-bear-encoding" }
mandelbrot_proof_baby_bear_transcript = { path = "../../capstones/mandelbrot-proof/baby-bear-transcript" }
mandelbrot_proof_kernel = { path = "../../capstones/mandelbrot-proof/kernel" }
parallel_ntt_webgpu = { path = "../../../ingots/parallel_ntt_webgpu" }
parallel_structure = { path = "../../../ingots/parallel_structure" }
poseidon_baby_bear = { path = "../../../ingots/poseidon_baby_bear" }
precision = { path = "../precision" }
region_layout = { path = "../../../ingots/region_layout" }
