//! Demo compile-gate: one pure-Rust test per curated `demos/**` Fe source
//! that lowers it through the REAL compiler pipeline (the same driver calls
//! `fe web build` makes: `resolve_web_entry` + `WebBundle::compile`) and
//! asserts it compiles. For render-mode demos the emitted WGSL is also
//! independently naga-reparsed and validated against the browser capability
//! set (no SHADER_INT64), mirroring `wasm_e2e.rs`/`spirv_e2e.rs`'s own gates.
//!
//! This is the ground-truth check `DEMO_MODERNIZATION_PLAN.md`'s
//! "compile-sweep" needed: every demo source listed here must keep compiling
//! against the pinned compiler, or this test fails and says exactly which
//! one broke and why. Pure Rust: no browser, no chrome, no python, no .mjs.
//!
//! GPU-execute is out of scope here (no adapter in this sandbox); the pass
//! bar is "compiles and naga-validates," the same honesty label
//! `spirv_e2e.rs` already uses ("validated, NOT executed").
//!
//! Coverage:
//!   - every `demos/sketches/*/src/lib.fe` that declares an `actor ... uses
//!     (GpuProgram<WebGpuBackend>)` (cga3d, qcga, desargues, mandelbrot,
//!     plasma, gradient, dec): entry/mode are DERIVED from the actor
//!     declaration, never hardcoded here, exactly as `fe web build` does
//!     with `--entry`/`--mode` omitted;
//!   - `demos/sketches/fmath`, a math-intrinsics library ingot with no
//!     render entry: diagnostics-only (it must still type-check);
//!   - `demos/sketches/qcga_pencil`: predates the `actor` idiom (spells the
//!     pattern out by hand across free `pub fn`s using `VertexStage`/
//!     `FragmentStage`, see the file's own commentary) and has its own
//!     staged `acceptance.rs` not yet wired into the workspace. No single
//!     `FragmentSurface` behavior exists to derive a render entry from, so
//!     this is a diagnostics-only gate (confirmed: `fe web build` without an
//!     explicit `--entry`/`--mode` fails closed with "no `actor` declaration
//!     to derive from", not a source diagnostic);
//!   - `demos/capstones/mandelbrot/kernel.fe`: a standalone, non-actor GRID
//!     kernel (intentionally target-neutral, four backends; see its own
//!     README), compiled here in explicit grid mode;
//!   - the two legacy interactive demos whose kernel is a bare `pub fn`
//!     fixture, not (yet) an `actor`: `webgpu-clifford-interactive`
//!     (`clifford_frag_rgba`) and `webgpu-mandelbrot-interactive`
//!     (`mandel_view_frag`). Their SSOT source lives at
//!     `crates/codegen/tests/fixtures/spirv/*.fe` (see each demo's
//!     `.gitignore`: "Generated by the Fe compiler via: cargo run -p
//!     fe-codegen --example gen_*_interactive_demo"), so this test compiles
//!     that exact fixture in explicit render mode;
//!   - the two legacy interactive demos that DO ship a full, tracked ingot
//!     under their `gen*/app` directory (the canonical `render`/`verify`/
//!     `oracle uses (HostEffect, MainThread, mut Dispatch<WebGpuBackend>)`
//!     lanes, pre-dating the `actor` idiom): `webgpu-qcga3d-quadric`
//!     (`demos/webgpu-qcga3d-quadric/gen/app`) and `webgpu-cga-inversion`
//!     (`demos/webgpu-cga-inversion/gen-schedule32/app`), compiled here
//!     directly from their tracked source with the canonical policy their
//!     own `gen_*_demo.rs` generator uses.

use std::path::{Path, PathBuf};

use common::InputDb;
use driver::DriverDataBase;
use fe_codegen::{WebBuildOptions, WebBundle, WebBundleMode, WebCanonicalPolicy, resolve_web_entry};
use hir::hir_def::HirIngot;
use url::Url;

fn repo_root() -> PathBuf {
    // CARGO_MANIFEST_DIR is `crates/codegen`; two ancestors up is the repo root.
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .and_then(Path::parent)
        .expect("crates/codegen should have a two-level ancestor (the repo root)")
        .to_path_buf()
}

/// Reparse the emitted WGSL with naga's `wgsl-in` front end and validate it
/// against the BROWSER capability set (`Capabilities::default()`, no
/// SHADER_INT64) -- independent of `WebBundle::compile`'s own internal gate
/// (belt and suspenders, matching the idiom every other e2e test here uses).
fn assert_browser_wgsl(wgsl: &str) {
    assert!(
        !wgsl.contains("i64") && !wgsl.contains("u64"),
        "browser-profile WGSL must contain no 64-bit scalar token:\n{wgsl}"
    );
    let module = naga::front::wgsl::parse_str(wgsl).unwrap_or_else(|e| {
        panic!("naga wgsl-in should reparse the emitted WGSL: {e:?}\n{wgsl}")
    });
    naga::valid::Validator::new(
        naga::valid::ValidationFlags::all(),
        naga::valid::Capabilities::default(),
    )
    .validate(&module)
    .unwrap_or_else(|e| panic!("browser-profile WGSL validation failed: {e:?}"));
}

/// Run `body` with a checked-in ingot directory's driver database and top
/// module. `body` receives `&DriverDataBase` (borrowed, not moved) so the
/// caller can keep compiling against it (`resolve_web_entry`,
/// `WebBundle::compile`, ...).
fn with_ingot<R>(rel_dir: &str, body: impl FnOnce(&DriverDataBase, hir::hir_def::TopLevelMod<'_>) -> R) -> R {
    let dir = repo_root().join(rel_dir);
    let mut db = DriverDataBase::default();
    let url = Url::from_directory_path(&dir)
        .unwrap_or_else(|_| panic!("invalid ingot path {}", dir.display()));
    assert!(
        !driver::init_ingot(&mut db, &url),
        "{rel_dir}: ingot initialization diagnostics"
    );
    let ingot = db
        .workspace()
        .containing_ingot(&db, url)
        .unwrap_or_else(|| panic!("{rel_dir} did not resolve to one ingot"));
    let top_mod = ingot.root_mod(&db);
    let diagnostics = db.run_on_top_mod(top_mod).format_diags(&db);
    assert!(
        diagnostics.is_empty(),
        "{rel_dir}: source diagnostics prevent compilation:\n{diagnostics}"
    );
    body(&db, top_mod)
}

/// Run `body` with a standalone `.fe` FILE (no `fe.toml`, a fixture path)
/// loaded into its own driver database.
fn with_standalone_file<R>(rel_path: &str, body: impl FnOnce(&DriverDataBase, hir::hir_def::TopLevelMod<'_>) -> R) -> R {
    let file_path = repo_root().join(rel_path);
    let source = std::fs::read_to_string(&file_path)
        .unwrap_or_else(|e| panic!("failed to read {}: {e}", file_path.display()));
    let mut db = DriverDataBase::default();
    let url = Url::from_file_path(&file_path)
        .unwrap_or_else(|_| panic!("invalid file path {}", file_path.display()));
    db.workspace().touch(&mut db, url.clone(), Some(source));
    let file = db
        .workspace()
        .get(&db, &url)
        .unwrap_or_else(|| panic!("failed to load {}", file_path.display()));
    let top_mod = db.top_mod(file);
    let diagnostics = db.run_on_top_mod(top_mod).format_diags(&db);
    assert!(
        diagnostics.is_empty(),
        "{rel_path}: source diagnostics prevent compilation:\n{diagnostics}"
    );
    body(&db, top_mod)
}

/// Compile an ingot directory whose render/grid entry is DERIVED from its
/// `actor ... uses (GpuProgram<WebGpuBackend>)` declaration, exactly as
/// `fe web build` does with `--entry`/`--mode` omitted.
fn compile_actor_ingot(rel_dir: &str) -> WebBundle {
    with_ingot(rel_dir, |db, top_mod| {
        let (entry, mode) = resolve_web_entry(db, top_mod, None, None).unwrap_or_else(|e| {
            panic!("{rel_dir}: could not derive a render entry from the actor declaration: {e}")
        });
        let options = match mode {
            WebBundleMode::Render => WebBuildOptions::render(entry, Some(rel_dir.to_string())),
            WebBundleMode::Grid => panic!(
                "{rel_dir}: derived grid mode; no curated sketch is expected to be grid-shaped"
            ),
        };
        WebBundle::compile(db, top_mod, options)
            .unwrap_or_else(|e| panic!("{rel_dir}: WebBundle::compile failed: {e}"))
    })
}

/// Compile a checked-in ingot directory in explicit render mode with the
/// canonical `render`/`verify`/`oracle` lanes required, matching the legacy
/// `render/verify/oracle uses (HostEffect, MainThread, mut
/// Dispatch<WebGpuBackend>)` demos' own `gen_*_demo.rs` generator.
fn compile_canonical_app(rel_dir: &str, entry: &str) -> WebBundle {
    with_ingot(rel_dir, |db, top_mod| {
        let options = WebBuildOptions::render(entry, Some(rel_dir.to_string()))
            .with_canonical_policy(WebCanonicalPolicy::Required)
            .with_canonical_entries(["render", "verify", "oracle"]);
        WebBundle::compile(db, top_mod, options)
            .unwrap_or_else(|e| panic!("{rel_dir}: WebBundle::compile failed: {e}"))
    })
}

/// Compile a standalone `.fe` fixture file in explicit render mode.
fn compile_standalone_render(rel_path: &str, entry: &str) -> WebBundle {
    with_standalone_file(rel_path, |db, top_mod| {
        let options = WebBuildOptions::render(entry, Some(rel_path.to_string()));
        WebBundle::compile(db, top_mod, options)
            .unwrap_or_else(|e| panic!("{rel_path}: WebBundle::compile failed: {e}"))
    })
}

/// Compile a standalone `.fe` fixture file in explicit grid mode.
fn compile_standalone_grid(rel_path: &str, entry: &str, workgroup: [u32; 3]) -> WebBundle {
    with_standalone_file(rel_path, |db, top_mod| {
        let options = WebBuildOptions::grid(entry, workgroup, Some(rel_path.to_string()));
        WebBundle::compile(db, top_mod, options)
            .unwrap_or_else(|e| panic!("{rel_path}: WebBundle::compile failed: {e}"))
    })
}

// ---------------------------------------------------------------------------
// R1a: the `std::web::view` vocabulary (Param/Extent/Surface) is ordinary
// const-constructible Fe living in std, not the compiler. This fixture
// const-constructs a `Surface` value through every constructor and must
// type-check clean with no compiler change.
// ---------------------------------------------------------------------------

#[test]
fn view_vocabulary_const_constructs_a_surface() {
    with_standalone_file(
        "crates/codegen/tests/fixtures/view/view_surface_smoke.fe",
        |_db, _top_mod| {},
    );
}

// ---------------------------------------------------------------------------
// Sketches (demos/sketches/*/src/lib.fe): each declares an `actor ... uses
// (GpuProgram<WebGpuBackend>)` with a single `FragmentSurface` behavior, so
// entry/mode are always DERIVED, never hardcoded here.
// ---------------------------------------------------------------------------

#[test]
fn cga3d_sketch_compiles() {
    let bundle = compile_actor_ingot("demos/sketches/cga3d");
    assert_browser_wgsl(&bundle.wgsl);
    wasmparser::validate(&bundle.wasm).expect("cga3d wasm should be valid");
}

#[test]
fn qcga_sketch_compiles() {
    let bundle = compile_actor_ingot("demos/sketches/qcga");
    assert_browser_wgsl(&bundle.wgsl);
    wasmparser::validate(&bundle.wasm).expect("qcga wasm should be valid");
}

#[test]
fn desargues_sketch_compiles() {
    let bundle = compile_actor_ingot("demos/sketches/desargues");
    assert_browser_wgsl(&bundle.wgsl);
    wasmparser::validate(&bundle.wasm).expect("desargues wasm should be valid");
}

#[test]
fn mandelbrot_sketch_compiles() {
    let bundle = compile_actor_ingot("demos/sketches/mandelbrot");
    assert_browser_wgsl(&bundle.wgsl);
    wasmparser::validate(&bundle.wasm).expect("mandelbrot sketch wasm should be valid");
}

// ---------------------------------------------------------------------------
// R3 step 1 (param gestures, mandelbrot): the gallery `demos/sketches/
// mandelbrot` actor's `update_view` behavior (the `UpdateSurface` role
// marker) is projected into the manifest `control` section AND compiled into
// `bundle.wasm` as a real, callable export. Fe owns pan sensitivity, the zoom
// curve, the cursor anchor, and the clamps; JS delivers only raw deltas.
//
// Gate: the manifest `control` section has the exact shape the runtime reads
// (measured, not assumed), and the wasmtime-executed `update_view` export
// matches an oracle over a seeded synthetic gesture tape at EVERY step,
// mirroring `spirv_e2e.rs`'s `update_view_matches_oracle_over_gesture_tape`
// rigor for the `mandel_view_ctl.fe` fixture's i32 Q12 sibling.
// ---------------------------------------------------------------------------

const MANDELBROT_CENTER_X_RANGE: (f32, f32) = (-2.5, 1.0);
const MANDELBROT_CENTER_Y_RANGE: (f32, f32) = (-1.5, 1.5);
// The df64 zoom floor (about 14 significant df64 digits gets a usable
// picture down to roughly 1e-11); mirrors `lib.fe`'s `ZOOM_MIN`.
const MANDELBROT_ZOOM_RANGE: (f32, f32) = (0.00000000001, 3.0);
const MANDELBROT_RES: f32 = 512.0;

/// Knuth's TwoSum, mirroring `lib.fe`'s `two_sum`: exact `a + b` as `(s, e)`
/// with `s + e == a + b` over the reals, plain f32 (no `f64`, no fused
/// multiply-add) so this stays bit-for-bit comparable to the wasm the same
/// source lowers to.
fn two_sum(a: f32, b: f32) -> (f32, f32) {
    let s = a + b;
    let bb = s - a;
    let err = (a - (s - bb)) + (b - bb);
    (s, err)
}

/// Mirrors `lib.fe`'s `df_add_f32`: df64 `a` plus a plain f32 `b`.
fn df_add_f32(a_hi: f32, a_lo: f32, b: f32) -> (f32, f32) {
    let (s, e0) = two_sum(a_hi, b);
    let e1 = e0 + a_lo;
    two_sum(s, e1)
}

/// Mirrors `lib.fe`'s `df_clamp`: clamp a df64 value to an f32 range,
/// comparing on `hi` only, dropping `lo` to zero on a clamp.
fn df_clamp(hi: f32, lo: f32, min_v: f32, max_v: f32) -> (f32, f32) {
    if hi < min_v {
        (min_v, 0.0)
    } else if hi > max_v {
        (max_v, 0.0)
    } else {
        (hi, lo)
    }
}

/// The independent oracle (re-derived from the pan/zoom/anchor/clamp spec:
/// pan follows the pointer via the actor's own pixel/complex-plane map, one
/// wheel notch is a fixed 7/8-in / 9/8-out zoom step, the anchor correction
/// uses the OLD zoom minus the NEW (clamped) zoom via that SAME map, clamps
/// apply last to the actor's declared `view()` ranges): `escape`'s own u/v
/// map is `u(px) = (px+0.5)/res*2-1` (screen right = complex right) and
/// `v(py) = 1-(py+0.5)/res*2` (screen DOWN = complex UP, the Y-flip), so a
/// downward drag increases `center_y` (opposite of the `dx`/`center_x` sign).
///
/// The complex-plane centre is df64 (deep zoom, `MANDELBROT_DF64_MB.md`
/// equivalent: see `lib.fe`'s module doc): pan and anchor deltas are O(zoom)
/// quantities that fold into the df64 centre through `df_add_f32`, mirroring
/// `lib.fe`'s `update_view` exactly (same op sequence, same f32 rounding),
/// so this oracle is expected to match the wasm export BIT-FOR-BIT, not just
/// within an epsilon.
fn mandelbrot_update_view_oracle(
    center_x_hi: f32,
    center_x_lo: f32,
    center_y_hi: f32,
    center_y_lo: f32,
    zoom: f32,
    res: f32,
    dx: f32,
    dy: f32,
    dzoom: f32,
    mx: f32,
    my: f32,
) -> (f32, f32, f32, f32, f32) {
    let step = 2.0 * zoom / res;
    let (cx0_hi, cx0_lo) = df_add_f32(center_x_hi, center_x_lo, -dx * step);
    let (cy0_hi, cy0_lo) = df_add_f32(center_y_hi, center_y_lo, dy * step);

    let stepped = if dzoom < 0.0 {
        zoom * 0.875
    } else if dzoom > 0.0 {
        zoom * 1.125
    } else {
        zoom
    };
    let z_c = stepped.clamp(MANDELBROT_ZOOM_RANGE.0, MANDELBROT_ZOOM_RANGE.1);

    let u = (mx + 0.5) * 2.0 / res - 1.0;
    let v = 1.0 - (my + 0.5) * 2.0 / res;
    let (cx_a_hi, cx_a_lo) = df_add_f32(cx0_hi, cx0_lo, u * (zoom - z_c));
    let (cy_a_hi, cy_a_lo) = df_add_f32(cy0_hi, cy0_lo, v * (zoom - z_c));

    let (cx_c_hi, cx_c_lo) =
        df_clamp(cx_a_hi, cx_a_lo, MANDELBROT_CENTER_X_RANGE.0, MANDELBROT_CENTER_X_RANGE.1);
    let (cy_c_hi, cy_c_lo) =
        df_clamp(cy_a_hi, cy_a_lo, MANDELBROT_CENTER_Y_RANGE.0, MANDELBROT_CENTER_Y_RANGE.1);
    (cx_c_hi, cx_c_lo, cy_c_hi, cy_c_lo, z_c)
}

/// The manifest `control` section has EXACTLY the shape the render runtime
/// reads: the `update_view` export, its 11 positional arg sources (5 raw
/// gesture deltas, then the actor's 6 df64-centre state fields by name, in
/// declaration order), and the 5-value reply's target field names.
#[test]
fn mandelbrot_control_manifest_projects_gesture_bindings() {
    use fe_codegen::WebControlArgSource as Src;

    let bundle = compile_actor_ingot("demos/sketches/mandelbrot");
    let control = bundle
        .manifest
        .control
        .as_ref()
        .expect("demos/sketches/mandelbrot should project an `UpdateSurface` control section");
    assert_eq!(control.export, "update_view");
    assert_eq!(
        control.args,
        vec![
            Src::Drag { axis: "x".to_string() },
            Src::Drag { axis: "y".to_string() },
            Src::Wheel,
            Src::Pointer { axis: "x".to_string() },
            Src::Pointer { axis: "y".to_string() },
            Src::State { name: "center_x_hi".to_string() },
            Src::State { name: "center_x_lo".to_string() },
            Src::State { name: "center_y_hi".to_string() },
            Src::State { name: "center_y_lo".to_string() },
            Src::State { name: "zoom".to_string() },
            Src::State { name: "res".to_string() },
        ],
        "control.args must be exactly [dx, dy, dzoom, mx, my] (the reserved gesture-arg \
         vocabulary) followed by the actor's state fields in declaration order"
    );
    assert_eq!(
        control.result,
        vec![
            "center_x_hi".to_string(),
            "center_x_lo".to_string(),
            "center_y_hi".to_string(),
            "center_y_lo".to_string(),
            "zoom".to_string(),
        ],
        "control.result must be the LEADING 5 state fields (declaration order); `res` is read \
         but not itself gesture-updated"
    );

    // Non-interactive sketches carry no `control` section at all (this is
    // exactly what keeps their manifests byte-stable): spot-check a sibling.
    let plain = compile_actor_ingot("demos/sketches/plasma");
    assert!(
        plain.manifest.control.is_none(),
        "a sketch with no `UpdateSurface` behavior must project no `control` section"
    );
}

/// The wasmtime-executed `update_view` export matches the independent oracle
/// over a deterministic synthetic gesture tape (a forced zoom-in burst, then
/// a seeded LCG mixed drag/wheel walk), feeding each reply forward as the
/// next state -- the exact runtime round-trip `fe-render-runtime.js`'s
/// `_applyGesture` performs. Asserts the clamps hold at every step and that
/// the tape visits every clamp arm (coverage, not just "never observed to
/// escape").
///
/// `ZOOM_MIN` is a df64-depth floor (`~1e-11`) a purely random 3-way `dzoom`
/// walk cannot reach in any reasonable step budget: reaching it from the
/// declared init (`1.5`) takes about `ln(1e-11/1.5)/ln(0.875) ~= 193`
/// CONSECUTIVE zoom-in notches, vanishingly unlikely at random (unlike
/// `ZOOM_MAX`, ~6 consecutive zoom-out notches away, which the random walk
/// reaches easily). So the tape runs the ORIGINAL random walk FIRST (the
/// regime that actually exercises the centre clamps: panning sensitivity is
/// `2*zoom/res`, so it needs zoom to stay near a normal size, not buried at
/// the df64 floor), then APPENDS `FORCE_ZOOM_IN_STEPS` deterministic zoom-in
/// notches (cursor centred, so the anchor term is exactly zero) to guarantee
/// `ZOOM_MIN` coverage from wherever the random walk left `zoom`. Every step,
/// forced or random, still runs through wasmtime and is checked against the
/// oracle.
#[test]
fn mandelbrot_update_view_matches_oracle_over_gesture_tape() {
    let bundle = compile_actor_ingot("demos/sketches/mandelbrot");
    let engine = wasmtime::Engine::default();
    let module =
        wasmtime::Module::new(&engine, &bundle.wasm).expect("wasmtime should load the module");
    let mut store = wasmtime::Store::new(&engine, ());
    let instance = wasmtime::Instance::new(&mut store, &module, &[])
        .expect("wasmtime should instantiate the mandelbrot sketch wasm");
    let update_view = instance
        .get_typed_func::<
            (f32, f32, f32, f32, f32, f32, f32, f32, f32, f32, f32),
            (f32, f32, f32, f32, f32),
        >(&mut store, "update_view")
        .expect(
            "`update_view` export should exist as (f32 x11) -> (f32, f32, f32, f32, f32): 5 \
             gesture args then the 6 flattened df64-centre actor state fields",
        );

    // view()'s declared init: `center_x_hi = -0.5`, `center_y_hi = 0.0`, both
    // df64 `_lo` words start at zero, `zoom = 1.5`.
    let (mut cx_hi, mut cx_lo, mut cy_hi, mut cy_lo, mut zoom) = (-0.5f32, 0.0f32, 0.0f32, 0.0f32, 1.5f32);
    let res = MANDELBROT_RES;

    let mut s: u64 = 0x5EED_1234_CAFE_F00D;
    let (mut hit_cx_lo, mut hit_cx_hi, mut hit_cy_lo, mut hit_cy_hi) = (0u32, 0u32, 0u32, 0u32);
    let (mut hit_zoom_lo, mut hit_zoom_hi) = (0u32, 0u32);
    const RANDOM_STEPS: usize = 3_000;
    // From the worst-case starting point the random phase can leave zoom at
    // (`ZOOM_MAX = 3.0`): `ln(1e-11/3.0)/ln(0.875) ~= 198`, so 220 gives
    // margin.
    const FORCE_ZOOM_IN_STEPS: usize = 220;
    const STEPS: usize = RANDOM_STEPS + FORCE_ZOOM_IN_STEPS;
    for step in 0..STEPS {
        let (dx, dy, dzoom, mx, my) = if step < RANDOM_STEPS {
            s = s
                .wrapping_mul(6364136223846793005)
                .wrapping_add(1442695040888963407);
            let r = s;
            // Wide pixel deltas (up to +-127px) and an occasionally
            // out-of-frame cursor so the walk actually reaches every centre
            // clamp, not just wanders near the default view.
            let dx = (((r >> 8) & 255) as i32 - 128) as f32;
            let dy = (((r >> 16) & 255) as i32 - 128) as f32;
            let dzoom = match (r >> 24) & 3 {
                0 => -1.0,
                1 => 1.0,
                _ => 0.0,
            };
            let mx = ((r >> 32) & 1023) as f32 - 256.0;
            let my = ((r >> 42) & 1023) as f32 - 256.0;
            (dx, dy, dzoom, mx, my)
        } else {
            // The deterministic zoom-in burst: no pan (dx=dy=0), cursor
            // centred (so the anchor term is exactly zero and the centre
            // does not drift), pure zoom-in.
            (0.0, 0.0, -1.0, res / 2.0, res / 2.0)
        };

        let got = update_view
            .call(
                &mut store,
                (dx, dy, dzoom, mx, my, cx_hi, cx_lo, cy_hi, cy_lo, zoom, res),
            )
            .expect("update_view should run");
        let want = mandelbrot_update_view_oracle(
            cx_hi, cx_lo, cy_hi, cy_lo, zoom, res, dx, dy, dzoom, mx, my,
        );
        assert_eq!(
            got, want,
            "gesture-tape step {step}: wasm update_view(cx_hi={cx_hi},cx_lo={cx_lo},\
             cy_hi={cy_hi},cy_lo={cy_lo},zoom={zoom}; dx={dx},dy={dy},dz={dzoom},mx={mx},my={my}) \
             = {got:?} must equal the oracle {want:?}"
        );

        (cx_hi, cx_lo, cy_hi, cy_lo, zoom) = got;
        if cx_hi <= MANDELBROT_CENTER_X_RANGE.0 {
            hit_cx_lo += 1;
        }
        if cx_hi >= MANDELBROT_CENTER_X_RANGE.1 {
            hit_cx_hi += 1;
        }
        if cy_hi <= MANDELBROT_CENTER_Y_RANGE.0 {
            hit_cy_lo += 1;
        }
        if cy_hi >= MANDELBROT_CENTER_Y_RANGE.1 {
            hit_cy_hi += 1;
        }
        if zoom <= MANDELBROT_ZOOM_RANGE.0 {
            hit_zoom_lo += 1;
        }
        if zoom >= MANDELBROT_ZOOM_RANGE.1 {
            hit_zoom_hi += 1;
        }
        assert!(
            (MANDELBROT_CENTER_X_RANGE.0..=MANDELBROT_CENTER_X_RANGE.1).contains(&cx_hi),
            "step {step}: center_x_hi {cx_hi} escaped its view() range"
        );
        assert!(
            (MANDELBROT_CENTER_Y_RANGE.0..=MANDELBROT_CENTER_Y_RANGE.1).contains(&cy_hi),
            "step {step}: center_y_hi {cy_hi} escaped its view() range"
        );
        assert!(
            (MANDELBROT_ZOOM_RANGE.0..=MANDELBROT_ZOOM_RANGE.1).contains(&zoom),
            "step {step}: zoom {zoom} escaped its view() range"
        );
    }

    assert!(
        hit_cx_lo > 0 && hit_cx_hi > 0 && hit_cy_lo > 0 && hit_cy_hi > 0,
        "the gesture tape must visit all four center clamps (cx_lo={hit_cx_lo}, cx_hi={hit_cx_hi}, \
         cy_lo={hit_cy_lo}, cy_hi={hit_cy_hi})"
    );
    assert!(
        hit_zoom_lo > 0 && hit_zoom_hi > 0,
        "the gesture tape must visit both zoom clamps (zoom_lo={hit_zoom_lo}, zoom_hi={hit_zoom_hi})"
    );
    eprintln!(
        "R3 step 1 tape: {STEPS} mixed pan/zoom/anchor events under wasmtime; the mandelbrot \
         update_view triple equals the independent oracle at EVERY step. Clamp coverage: \
         cx_lo={hit_cx_lo} cx_hi={hit_cx_hi} cy_lo={hit_cy_lo} cy_hi={hit_cy_hi} \
         zoom_lo={hit_zoom_lo} zoom_hi={hit_zoom_hi}."
    );
}

#[test]
fn plasma_sketch_compiles() {
    let bundle = compile_actor_ingot("demos/sketches/plasma");
    assert_browser_wgsl(&bundle.wgsl);
    wasmparser::validate(&bundle.wasm).expect("plasma wasm should be valid");
}

#[test]
fn gradient_sketch_compiles() {
    let bundle = compile_actor_ingot("demos/sketches/gradient");
    assert_browser_wgsl(&bundle.wgsl);
    wasmparser::validate(&bundle.wasm).expect("gradient wasm should be valid");
}

#[test]
fn dec_sketch_compiles() {
    let bundle = compile_actor_ingot("demos/sketches/dec");
    assert_browser_wgsl(&bundle.wgsl);
    wasmparser::validate(&bundle.wasm).expect("dec wasm should be valid");
}

// ---------------------------------------------------------------------------
// Library / not-yet-wrapped sketches: no single `FragmentSurface` behavior to
// derive a render entry from, so these gate on source diagnostics only.
// ---------------------------------------------------------------------------

/// `fmath` is a math-intrinsics helper ingot consumed by `cga3d`/`qcga`/
/// `plasma` (via `fmath = "../fmath"` in their `fe.toml`); it declares no
/// actor and is not independently render-buildable. Gate: it must type-check
/// clean on its own.
#[test]
fn fmath_library_ingot_typechecks() {
    with_ingot("demos/sketches/fmath", |_db, _top_mod| {});
}

/// `qcga_pencil` predates the `actor` idiom: it spells the render program by
/// hand across free `pub fn`s (`surface_vertex uses (VertexStage<..>)`,
/// `surface_fragment uses (FragmentStage<..>)`, `render`/`verify uses
/// (HostEffect, MainThread, mut Dispatch<..>)`), documented in the file's
/// own commentary as a deliberate stopgap pending real `actor`/`behavior`
/// syntax. Confirmed via `fe web build demos/sketches/qcga_pencil` (no
/// `--entry`/`--mode`): the failure is "no `actor` declaration to derive
/// from", NOT a source diagnostic - there is no single-entry web bundle to
/// derive here (a vertex+fragment pair, not one `FragmentSurface`). This has
/// its own staged `acceptance.rs` (explicitly `#[allow(dead_code)]`-style,
/// not yet a workspace member) and is a documented coverage gap in
/// DEMO_MODERNIZATION_PLAN.md, not a broken demo. Gate: the ingot itself
/// must still type-check clean.
#[test]
fn qcga_pencil_sketch_typechecks() {
    with_ingot("demos/sketches/qcga_pencil", |_db, _top_mod| {});
}

// ---------------------------------------------------------------------------
// Capstone: a standalone, non-actor GRID kernel (deliberately target-neutral
// across EVM/Wasm/Native/SPIR-V; see demos/capstones/mandelbrot/README.md).
// ---------------------------------------------------------------------------

#[test]
fn capstone_mandelbrot_kernel_compiles() {
    let bundle = compile_standalone_grid(
        "demos/capstones/mandelbrot/kernel.fe",
        "mandel_pixel_q12",
        [8, 8, 1],
    );
    assert_browser_wgsl(&bundle.wgsl);
    wasmparser::validate(&bundle.wasm).expect("mandelbrot capstone wasm should be valid");
}

// ---------------------------------------------------------------------------
// Legacy interactive demos whose kernel is a bare `pub fn` fixture (no
// `actor` yet). SSOT is the fixture file under crates/codegen/tests/fixtures
// (see each demo's own `.gitignore`), compiled here in explicit render mode.
// ---------------------------------------------------------------------------

#[test]
fn clifford_interactive_frag_compiles() {
    let bundle = compile_standalone_render(
        "crates/codegen/tests/fixtures/spirv/clifford_frag_rgba.fe",
        "clifford_frag_rgba",
    );
    assert_browser_wgsl(&bundle.wgsl);
    wasmparser::validate(&bundle.wasm).expect("clifford_frag_rgba wasm should be valid");
}

#[test]
fn mandelbrot_interactive_frag_compiles() {
    let bundle = compile_standalone_render(
        "crates/codegen/tests/fixtures/spirv/mandel_view_frag.fe",
        "mandel_view_frag",
    );
    assert_browser_wgsl(&bundle.wgsl);
    wasmparser::validate(&bundle.wasm).expect("mandel_view_frag wasm should be valid");
}

// ---------------------------------------------------------------------------
// Legacy interactive demos that ship a full, tracked ingot under gen*/app:
// the canonical render/verify/oracle lanes, pre-dating the `actor` idiom.
// Compiled here from the exact tracked source, with the canonical policy
// each demo's own gen_*_demo.rs generator uses.
// ---------------------------------------------------------------------------

#[test]
fn qcga3d_quadric_app_compiles() {
    let bundle = compile_canonical_app(
        "demos/webgpu-qcga3d-quadric/gen/app",
        "qcga3d_sparse_planned_render",
    );
    assert_browser_wgsl(&bundle.wgsl);
    wasmparser::validate(&bundle.wasm).expect("qcga3d-quadric wasm should be valid");
}

#[test]
fn cga_inversion_schedule32_app_compiles() {
    let bundle = compile_canonical_app(
        "demos/webgpu-cga-inversion/gen-schedule32/app",
        "cga_schedule32_vec5_de_render",
    );
    assert_browser_wgsl(&bundle.wgsl);
    wasmparser::validate(&bundle.wasm).expect("cga-inversion schedule32 wasm should be valid");
}
