//! Demo compile-gate: one pure-Rust test per curated `demos/**` Fe source
//! that lowers it through the REAL compiler pipeline (the same driver calls
//! `fe web build` makes: `resolve_web_entry` + `WebBundle::compile`) and
//! asserts it compiles. For render-mode demos the emitted WGSL is also
//! independently naga-reparsed and validated against the browser capability
//! set (no SHADER_INT64), mirroring `wasm_e2e.rs`/`spirv_e2e.rs`'s own gates.
//!
//! This is the ground-truth check `DEMO_MODERNIZATION_PLAN.md`'s
//! "compile-sweep" needed: every demo source listed here must keep compiling
//! against the pinned compiler, or this test fails and says exactly which
//! one broke and why. Pure Rust: no browser, no chrome, no python, no .mjs.
//!
//! GPU-execute is out of scope here (no adapter in this sandbox); the pass
//! bar is "compiles and naga-validates," the same honesty label
//! `spirv_e2e.rs` already uses ("validated, NOT executed").
//!
//! Coverage:
//!   - every `demos/sketches/*/src/lib.fe` that declares an `actor ... uses
//!     (GpuProgram<WebGpuBackend>)` (cga3d, qcga, desargues, mandelbrot,
//!     plasma, gradient, dec): entry/mode are DERIVED from the actor
//!     declaration, never hardcoded here, exactly as `fe web build` does
//!     with `--entry`/`--mode` omitted;
//!   - `demos/sketches/fmath`, a math-intrinsics library ingot with no
//!     render entry: diagnostics-only (it must still type-check);
//!   - `demos/sketches/qcga_pencil`: predates the `actor` idiom (spells the
//!     pattern out by hand across free `pub fn`s using `VertexStage`/
//!     `FragmentStage`, see the file's own commentary) and has its own
//!     staged `acceptance.rs` not yet wired into the workspace. No single
//!     `FragmentSurface` behavior exists to derive a render entry from, so
//!     this is a diagnostics-only gate (confirmed: `fe web build` without an
//!     explicit `--entry`/`--mode` fails closed with "no `actor` declaration
//!     to derive from", not a source diagnostic);
//!   - `demos/capstones/mandelbrot/kernel.fe`: a standalone, non-actor GRID
//!     kernel (intentionally target-neutral, four backends; see its own
//!     README), compiled here in explicit grid mode;
//!   - the two legacy interactive demos whose kernel is a bare `pub fn`
//!     fixture, not (yet) an `actor`: `webgpu-clifford-interactive`
//!     (`clifford_frag_rgba`) and `webgpu-mandelbrot-interactive`
//!     (`mandel_view_frag`). Their SSOT source lives at
//!     `crates/codegen/tests/fixtures/spirv/*.fe` (see each demo's
//!     `.gitignore`: "Generated by the Fe compiler via: cargo run -p
//!     fe-codegen --example gen_*_interactive_demo"), so this test compiles
//!     that exact fixture in explicit render mode;
//!   - the two legacy interactive demos that DO ship a full, tracked ingot
//!     under their `gen*/app` directory (the canonical `render`/`verify`/
//!     `oracle uses (HostEffect, MainThread, mut Dispatch<WebGpuBackend>)`
//!     lanes, pre-dating the `actor` idiom): `webgpu-qcga3d-quadric`
//!     (`demos/webgpu-qcga3d-quadric/gen/app`) and `webgpu-cga-inversion`
//!     (`demos/webgpu-cga-inversion/gen-schedule32/app`), compiled here
//!     directly from their tracked source with the canonical policy their
//!     own `gen_*_demo.rs` generator uses.

use std::path::{Path, PathBuf};

use common::InputDb;
use driver::DriverDataBase;
use fe_codegen::{WebBuildOptions, WebBundle, WebBundleMode, WebCanonicalPolicy, resolve_web_entry};
use hir::hir_def::HirIngot;
use url::Url;

fn repo_root() -> PathBuf {
    // CARGO_MANIFEST_DIR is `crates/codegen`; two ancestors up is the repo root.
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .and_then(Path::parent)
        .expect("crates/codegen should have a two-level ancestor (the repo root)")
        .to_path_buf()
}

/// Reparse the emitted WGSL with naga's `wgsl-in` front end and validate it
/// against the BROWSER capability set (`Capabilities::default()`, no
/// SHADER_INT64) -- independent of `WebBundle::compile`'s own internal gate
/// (belt and suspenders, matching the idiom every other e2e test here uses).
fn assert_browser_wgsl(wgsl: &str) {
    assert!(
        !wgsl.contains("i64") && !wgsl.contains("u64"),
        "browser-profile WGSL must contain no 64-bit scalar token:\n{wgsl}"
    );
    let module = naga::front::wgsl::parse_str(wgsl).unwrap_or_else(|e| {
        panic!("naga wgsl-in should reparse the emitted WGSL: {e:?}\n{wgsl}")
    });
    naga::valid::Validator::new(
        naga::valid::ValidationFlags::all(),
        naga::valid::Capabilities::default(),
    )
    .validate(&module)
    .unwrap_or_else(|e| panic!("browser-profile WGSL validation failed: {e:?}"));
}

/// Run `body` with a checked-in ingot directory's driver database and top
/// module. `body` receives `&DriverDataBase` (borrowed, not moved) so the
/// caller can keep compiling against it (`resolve_web_entry`,
/// `WebBundle::compile`, ...).
fn with_ingot<R>(rel_dir: &str, body: impl FnOnce(&DriverDataBase, hir::hir_def::TopLevelMod<'_>) -> R) -> R {
    let dir = repo_root().join(rel_dir);
    let mut db = DriverDataBase::default();
    let url = Url::from_directory_path(&dir)
        .unwrap_or_else(|_| panic!("invalid ingot path {}", dir.display()));
    assert!(
        !driver::init_ingot(&mut db, &url),
        "{rel_dir}: ingot initialization diagnostics"
    );
    let ingot = db
        .workspace()
        .containing_ingot(&db, url)
        .unwrap_or_else(|| panic!("{rel_dir} did not resolve to one ingot"));
    let top_mod = ingot.root_mod(&db);
    let diagnostics = db.run_on_top_mod(top_mod).format_diags(&db);
    assert!(
        diagnostics.is_empty(),
        "{rel_dir}: source diagnostics prevent compilation:\n{diagnostics}"
    );
    body(&db, top_mod)
}

/// Run `body` with a standalone `.fe` FILE (no `fe.toml`, a fixture path)
/// loaded into its own driver database.
fn with_standalone_file<R>(rel_path: &str, body: impl FnOnce(&DriverDataBase, hir::hir_def::TopLevelMod<'_>) -> R) -> R {
    let file_path = repo_root().join(rel_path);
    let source = std::fs::read_to_string(&file_path)
        .unwrap_or_else(|e| panic!("failed to read {}: {e}", file_path.display()));
    let mut db = DriverDataBase::default();
    let url = Url::from_file_path(&file_path)
        .unwrap_or_else(|_| panic!("invalid file path {}", file_path.display()));
    db.workspace().touch(&mut db, url.clone(), Some(source));
    let file = db
        .workspace()
        .get(&db, &url)
        .unwrap_or_else(|| panic!("failed to load {}", file_path.display()));
    let top_mod = db.top_mod(file);
    let diagnostics = db.run_on_top_mod(top_mod).format_diags(&db);
    assert!(
        diagnostics.is_empty(),
        "{rel_path}: source diagnostics prevent compilation:\n{diagnostics}"
    );
    body(&db, top_mod)
}

/// Compile an ingot directory whose render/grid entry is DERIVED from its
/// `actor ... uses (GpuProgram<WebGpuBackend>)` declaration, exactly as
/// `fe web build` does with `--entry`/`--mode` omitted.
fn compile_actor_ingot(rel_dir: &str) -> WebBundle {
    with_ingot(rel_dir, |db, top_mod| {
        let (entry, mode) = resolve_web_entry(db, top_mod, None, None).unwrap_or_else(|e| {
            panic!("{rel_dir}: could not derive a render entry from the actor declaration: {e}")
        });
        let options = match mode {
            WebBundleMode::Render => WebBuildOptions::render(entry, Some(rel_dir.to_string())),
            WebBundleMode::Grid => panic!(
                "{rel_dir}: derived grid mode; no curated sketch is expected to be grid-shaped"
            ),
        };
        WebBundle::compile(db, top_mod, options)
            .unwrap_or_else(|e| panic!("{rel_dir}: WebBundle::compile failed: {e}"))
    })
}

/// Compile a checked-in ingot directory in explicit render mode with the
/// canonical `render`/`verify`/`oracle` lanes required, matching the legacy
/// `render/verify/oracle uses (HostEffect, MainThread, mut
/// Dispatch<WebGpuBackend>)` demos' own `gen_*_demo.rs` generator.
fn compile_canonical_app(rel_dir: &str, entry: &str) -> WebBundle {
    with_ingot(rel_dir, |db, top_mod| {
        let options = WebBuildOptions::render(entry, Some(rel_dir.to_string()))
            .with_canonical_policy(WebCanonicalPolicy::Required)
            .with_canonical_entries(["render", "verify", "oracle"]);
        WebBundle::compile(db, top_mod, options)
            .unwrap_or_else(|e| panic!("{rel_dir}: WebBundle::compile failed: {e}"))
    })
}

/// Compile a standalone `.fe` fixture file in explicit render mode.
fn compile_standalone_render(rel_path: &str, entry: &str) -> WebBundle {
    with_standalone_file(rel_path, |db, top_mod| {
        let options = WebBuildOptions::render(entry, Some(rel_path.to_string()));
        WebBundle::compile(db, top_mod, options)
            .unwrap_or_else(|e| panic!("{rel_path}: WebBundle::compile failed: {e}"))
    })
}

/// Compile a standalone `.fe` fixture file in explicit grid mode.
fn compile_standalone_grid(rel_path: &str, entry: &str, workgroup: [u32; 3]) -> WebBundle {
    with_standalone_file(rel_path, |db, top_mod| {
        let options = WebBuildOptions::grid(entry, workgroup, Some(rel_path.to_string()));
        WebBundle::compile(db, top_mod, options)
            .unwrap_or_else(|e| panic!("{rel_path}: WebBundle::compile failed: {e}"))
    })
}

// ---------------------------------------------------------------------------
// R1a: the `std::web::view` vocabulary (Param/Extent/Surface) is ordinary
// const-constructible Fe living in std, not the compiler. This fixture
// const-constructs a `Surface` value through every constructor and must
// type-check clean with no compiler change.
// ---------------------------------------------------------------------------

#[test]
fn view_vocabulary_const_constructs_a_surface() {
    with_standalone_file(
        "crates/codegen/tests/fixtures/view/view_surface_smoke.fe",
        |_db, _top_mod| {},
    );
}

// ---------------------------------------------------------------------------
// Sketches (demos/sketches/*/src/lib.fe): each declares an `actor ... uses
// (GpuProgram<WebGpuBackend>)` with a single `FragmentSurface` behavior, so
// entry/mode are always DERIVED, never hardcoded here.
// ---------------------------------------------------------------------------

#[test]
fn cga3d_sketch_compiles() {
    let bundle = compile_actor_ingot("demos/sketches/cga3d");
    assert_browser_wgsl(&bundle.wgsl);
    wasmparser::validate(&bundle.wasm).expect("cga3d wasm should be valid");
}

#[test]
fn qcga_sketch_compiles() {
    let bundle = compile_actor_ingot("demos/sketches/qcga");
    assert_browser_wgsl(&bundle.wgsl);
    wasmparser::validate(&bundle.wasm).expect("qcga wasm should be valid");
}

#[test]
fn desargues_sketch_compiles() {
    let bundle = compile_actor_ingot("demos/sketches/desargues");
    assert_browser_wgsl(&bundle.wgsl);
    wasmparser::validate(&bundle.wasm).expect("desargues wasm should be valid");
}

#[test]
fn mandelbrot_sketch_compiles() {
    let bundle = compile_actor_ingot("demos/sketches/mandelbrot");
    assert_browser_wgsl(&bundle.wgsl);
    wasmparser::validate(&bundle.wasm).expect("mandelbrot sketch wasm should be valid");
}

#[test]
fn plasma_sketch_compiles() {
    let bundle = compile_actor_ingot("demos/sketches/plasma");
    assert_browser_wgsl(&bundle.wgsl);
    wasmparser::validate(&bundle.wasm).expect("plasma wasm should be valid");
}

#[test]
fn gradient_sketch_compiles() {
    let bundle = compile_actor_ingot("demos/sketches/gradient");
    assert_browser_wgsl(&bundle.wgsl);
    wasmparser::validate(&bundle.wasm).expect("gradient wasm should be valid");
}

#[test]
fn dec_sketch_compiles() {
    let bundle = compile_actor_ingot("demos/sketches/dec");
    assert_browser_wgsl(&bundle.wgsl);
    wasmparser::validate(&bundle.wasm).expect("dec wasm should be valid");
}

// ---------------------------------------------------------------------------
// Library / not-yet-wrapped sketches: no single `FragmentSurface` behavior to
// derive a render entry from, so these gate on source diagnostics only.
// ---------------------------------------------------------------------------

/// `fmath` is a math-intrinsics helper ingot consumed by `cga3d`/`qcga`/
/// `plasma` (via `fmath = "../fmath"` in their `fe.toml`); it declares no
/// actor and is not independently render-buildable. Gate: it must type-check
/// clean on its own.
#[test]
fn fmath_library_ingot_typechecks() {
    with_ingot("demos/sketches/fmath", |_db, _top_mod| {});
}

/// `qcga_pencil` predates the `actor` idiom: it spells the render program by
/// hand across free `pub fn`s (`surface_vertex uses (VertexStage<..>)`,
/// `surface_fragment uses (FragmentStage<..>)`, `render`/`verify uses
/// (HostEffect, MainThread, mut Dispatch<..>)`), documented in the file's
/// own commentary as a deliberate stopgap pending real `actor`/`behavior`
/// syntax. Confirmed via `fe web build demos/sketches/qcga_pencil` (no
/// `--entry`/`--mode`): the failure is "no `actor` declaration to derive
/// from", NOT a source diagnostic - there is no single-entry web bundle to
/// derive here (a vertex+fragment pair, not one `FragmentSurface`). This has
/// its own staged `acceptance.rs` (explicitly `#[allow(dead_code)]`-style,
/// not yet a workspace member) and is a documented coverage gap in
/// DEMO_MODERNIZATION_PLAN.md, not a broken demo. Gate: the ingot itself
/// must still type-check clean.
#[test]
fn qcga_pencil_sketch_typechecks() {
    with_ingot("demos/sketches/qcga_pencil", |_db, _top_mod| {});
}

// ---------------------------------------------------------------------------
// Capstone: a standalone, non-actor GRID kernel (deliberately target-neutral
// across EVM/Wasm/Native/SPIR-V; see demos/capstones/mandelbrot/README.md).
// ---------------------------------------------------------------------------

#[test]
fn capstone_mandelbrot_kernel_compiles() {
    let bundle = compile_standalone_grid(
        "demos/capstones/mandelbrot/kernel.fe",
        "mandel_pixel_q12",
        [8, 8, 1],
    );
    assert_browser_wgsl(&bundle.wgsl);
    wasmparser::validate(&bundle.wasm).expect("mandelbrot capstone wasm should be valid");
}

// ---------------------------------------------------------------------------
// Legacy interactive demos whose kernel is a bare `pub fn` fixture (no
// `actor` yet). SSOT is the fixture file under crates/codegen/tests/fixtures
// (see each demo's own `.gitignore`), compiled here in explicit render mode.
// ---------------------------------------------------------------------------

#[test]
fn clifford_interactive_frag_compiles() {
    let bundle = compile_standalone_render(
        "crates/codegen/tests/fixtures/spirv/clifford_frag_rgba.fe",
        "clifford_frag_rgba",
    );
    assert_browser_wgsl(&bundle.wgsl);
    wasmparser::validate(&bundle.wasm).expect("clifford_frag_rgba wasm should be valid");
}

#[test]
fn mandelbrot_interactive_frag_compiles() {
    let bundle = compile_standalone_render(
        "crates/codegen/tests/fixtures/spirv/mandel_view_frag.fe",
        "mandel_view_frag",
    );
    assert_browser_wgsl(&bundle.wgsl);
    wasmparser::validate(&bundle.wasm).expect("mandel_view_frag wasm should be valid");
}

// ---------------------------------------------------------------------------
// Legacy interactive demos that ship a full, tracked ingot under gen*/app:
// the canonical render/verify/oracle lanes, pre-dating the `actor` idiom.
// Compiled here from the exact tracked source, with the canonical policy
// each demo's own gen_*_demo.rs generator uses.
// ---------------------------------------------------------------------------

#[test]
fn qcga3d_quadric_app_compiles() {
    let bundle = compile_canonical_app(
        "demos/webgpu-qcga3d-quadric/gen/app",
        "qcga3d_sparse_planned_render",
    );
    assert_browser_wgsl(&bundle.wgsl);
    wasmparser::validate(&bundle.wasm).expect("qcga3d-quadric wasm should be valid");
}

#[test]
fn cga_inversion_schedule32_app_compiles() {
    let bundle = compile_canonical_app(
        "demos/webgpu-cga-inversion/gen-schedule32/app",
        "cga_schedule32_vec5_de_render",
    );
    assert_browser_wgsl(&bundle.wgsl);
    wasmparser::validate(&bundle.wasm).expect("cga-inversion schedule32 wasm should be valid");
}
