//! Independent state oracle for Event Studio's rich typed mailbox.
//!
//! Wasmtime executes the authored resident Fe transition over viewport,
//! pointer/touch, wheel, visibility, paced frame/timer, failure, and lifecycle
//! facts. A separate Rust reducer derives semantic state; generated bytes and
//! layout coincidence are not the correctness oracle.

use common::InputDb;
use driver::DriverDataBase;
use fe_codegen::{
    RESIDENT_ACTOR_INITIALIZE_EXPORT, RESIDENT_ACTOR_TRANSITION_EXPORT, compile_resident_actor,
};
use hir::hir_def::HirIngot;
use url::Url;

const STATE_LEAVES: usize = 18;
const EVENT_LEAVES: usize = 34;

#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
struct Model {
    width: u32,
    height: u32,
    pixel_ratio_percent: u32,
    observations: u32,
    pointer_x: u32,
    pointer_y: u32,
    pointer_events: u32,
    wheel_events: u32,
    visible: bool,
    visibility_events: u32,
    frame_events: u32,
    timer_events: u32,
    frame_timestamp: u32,
    bounded_drops: u32,
    latest_value: u32,
    failures: u32,
    connected: bool,
}

#[derive(Debug, Clone, Copy, Default)]
struct Event {
    kind: u32,
    target: u32,
    viewport_width: f32,
    viewport_height: f32,
    viewport_dpr: f32,
    pointer_phase: u32,
    pointer_device: u32,
    pointer_x: f32,
    pointer_y: f32,
    wheel_mode: u32,
    document_hidden: bool,
    frame_timestamp: f32,
    bounded_drops: u32,
    latest_value: u32,
}

fn bounded_dimension(value: f32) -> u32 {
    if value.is_finite() && (0.0..=100_000.0).contains(&value) {
        value as u32
    } else {
        100_000
    }
}

fn bounded_position(value: f32) -> u32 {
    if value.is_nan() || value > 100_000.0 {
        100_000
    } else if value < 0.0 {
        0
    } else {
        value as u32
    }
}

fn reduce(mut model: Model, event: Event) -> Model {
    match event.kind {
        0 => model.connected = true,
        1 => model.connected = false,
        13 if model.connected => match event.target {
            1 => {
                model.width = bounded_dimension(event.viewport_width);
                model.height = bounded_dimension(event.viewport_height);
                model.pixel_ratio_percent = bounded_dimension(event.viewport_dpr * 100.0);
                model.observations += 1;
            }
            2 => {
                model.pointer_x = bounded_position(event.pointer_x);
                model.pointer_y = bounded_position(event.pointer_y);
                model.pointer_events += 1;
                model.bounded_drops = event.bounded_drops;
            }
            3 => {
                model.pointer_x = bounded_position(event.pointer_x);
                model.pointer_y = bounded_position(event.pointer_y);
                model.wheel_events += 1;
                model.bounded_drops = event.bounded_drops;
            }
            4 => model.failures += 1,
            5 => {
                model.visible = !event.document_hidden;
                model.visibility_events += 1;
            }
            6 => {
                model.frame_timestamp = bounded_dimension(event.frame_timestamp);
                model.frame_events += 1;
            }
            7 => {
                model.timer_events += 1;
                model.latest_value = event.latest_value;
            }
            _ => {}
        },
        _ => {}
    }
    model
}

fn event_values(event: Event) -> Vec<wasmtime::Val> {
    vec![
        wasmtime::Val::I32(event.kind as i32),
        wasmtime::Val::I32(event.target as i32),
        wasmtime::Val::I32(0),
        wasmtime::Val::I32(0),
        wasmtime::Val::I32(0),
        wasmtime::Val::F32(0.0f32.to_bits()),
        wasmtime::Val::F32(0.0f32.to_bits()),
        wasmtime::Val::I32(0),
        wasmtime::Val::I32(0),
        wasmtime::Val::F32(event.viewport_width.to_bits()),
        wasmtime::Val::F32(event.viewport_height.to_bits()),
        wasmtime::Val::F32(event.viewport_dpr.to_bits()),
        wasmtime::Val::I32(event.pointer_phase as i32),
        wasmtime::Val::I32(event.pointer_device as i32),
        wasmtime::Val::I32(17),
        wasmtime::Val::F32(event.pointer_x.to_bits()),
        wasmtime::Val::F32(event.pointer_y.to_bits()),
        wasmtime::Val::I32(1),
        wasmtime::Val::I32(1),
        wasmtime::Val::F32(0.625f32.to_bits()),
        wasmtime::Val::F32(8.5f32.to_bits()),
        wasmtime::Val::I32(event.bounded_drops as i32),
        wasmtime::Val::F32(0.0f32.to_bits()),
        wasmtime::Val::F32((-4.5f32).to_bits()),
        wasmtime::Val::F32(0.0f32.to_bits()),
        wasmtime::Val::I32(event.wheel_mode as i32),
        wasmtime::Val::F32(event.pointer_x.to_bits()),
        wasmtime::Val::F32(event.pointer_y.to_bits()),
        wasmtime::Val::I32(0),
        wasmtime::Val::F32(9.5f32.to_bits()),
        wasmtime::Val::I32(event.document_hidden as i32),
        wasmtime::Val::F32(event.frame_timestamp.to_bits()),
        wasmtime::Val::I32(1),
        wasmtime::Val::I32(event.latest_value as i32),
    ]
}

fn state_values(values: &[wasmtime::Val]) -> Model {
    let words = values
        .iter()
        .map(|value| match value {
            wasmtime::Val::I32(value) => *value as u32,
            other => panic!("Event Studio returned non-i32 state leaf {other:?}"),
        })
        .collect::<Vec<_>>();
    Model {
        width: words[1],
        height: words[2],
        pixel_ratio_percent: words[3],
        observations: words[4],
        pointer_x: words[5],
        pointer_y: words[6],
        pointer_events: words[7],
        wheel_events: words[8],
        visible: words[9] != 0,
        visibility_events: words[10],
        frame_events: words[11],
        timer_events: words[12],
        frame_timestamp: words[13],
        bounded_drops: words[14],
        latest_value: words[15],
        failures: words[16],
        connected: words[17] != 0,
    }
}

#[test]
fn event_studio_matches_independent_browser_stream_and_lifecycle_oracle() {
    let path = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("../../demos/sketches/event_studio")
        .canonicalize()
        .expect("Event Studio ingot path");
    let url = Url::from_directory_path(path).expect("Event Studio URL");
    let mut db = DriverDataBase::default();
    assert!(
        !driver::init_ingot(&mut db, &url),
        "Event Studio diagnostics"
    );
    let ingot = db.workspace().containing_ingot(&db, url).unwrap();
    let top_mod = ingot.root_mod(&db);
    let diagnostics = db.run_on_top_mod(top_mod).format_diags(&db);
    assert!(
        diagnostics.is_empty(),
        "Event Studio diagnostics:\n{diagnostics}"
    );

    let artifact = compile_resident_actor(&db, top_mod)
        .expect("Event Studio contract")
        .expect("Event Studio actor");
    assert_eq!(artifact.contract.event_leaf_count, EVENT_LEAVES);
    assert_eq!(artifact.contract.state_leaf_count, STATE_LEAVES);
    assert_eq!(
        artifact.contract.scoped_task_source_entries,
        [
            "watch_viewport",
            "watch_gestures",
            "watch_visibility",
            "watch_frame_clock"
        ]
    );

    let engine = wasmtime::Engine::default();
    let module = wasmtime::Module::new(&engine, &artifact.wasm).unwrap();
    let mut store = wasmtime::Store::new(&engine, ());
    let mut linker = wasmtime::Linker::new(&engine);
    linker
        .func_wrap(
            "fe:web-window",
            "viewport_begin",
            |_seen: i32, _width: f32, _height: f32, _dpr: f32| -> i32 { 0 },
        )
        .unwrap();
    linker
        .func_wrap("fe:web-window", "animation_frame_begin", || -> i32 { 0 })
        .unwrap();
    linker
        .func_wrap(
            "fe:web-document",
            "visibility_begin",
            |_seen: i32, _previous_hidden: i32| -> i32 { 0 },
        )
        .unwrap();
    linker
        .func_wrap("fe:host", "sleep_begin", |_milliseconds: i64| -> i32 { 0 })
        .unwrap();
    linker
        .func_wrap(
            "fe:host",
            "select_begin",
            |_left: i32, _right: i32| -> i32 { 0 },
        )
        .unwrap();
    linker
        .func_wrap("fe:web-component-events", "pointer_begin", || -> i32 { 0 })
        .unwrap();
    linker
        .func_wrap("fe:web-component-events", "wheel_begin", || -> i32 { 0 })
        .unwrap();
    let send_type = module
        .imports()
        .find(|import| import.module() == "fe:actor" && import.name() == "send_begin")
        .expect("typed actor sink import")
        .ty()
        .unwrap_func()
        .clone();
    linker
        .func_new(
            "fe:actor",
            "send_begin",
            send_type,
            |_caller, _params, results| {
                results[0] = wasmtime::Val::I32(0);
                Ok(())
            },
        )
        .unwrap();
    let instance = linker.instantiate(&mut store, &module).unwrap();
    let initialize = instance
        .get_func(&mut store, RESIDENT_ACTOR_INITIALIZE_EXPORT)
        .unwrap();
    let transition = instance
        .get_func(&mut store, RESIDENT_ACTOR_TRANSITION_EXPORT)
        .unwrap();
    let mut initial = vec![wasmtime::Val::I32(0); STATE_LEAVES];
    initialize.call(&mut store, &[], &mut initial).unwrap();
    let mut expected = Model::default();
    assert_eq!(state_values(&initial), expected);

    let tape = [
        Event {
            kind: 13,
            target: 1,
            viewport_width: 900.0,
            viewport_height: 700.0,
            viewport_dpr: 2.0,
            ..Event::default()
        },
        Event {
            kind: 0,
            ..Event::default()
        },
        Event {
            kind: 13,
            target: 1,
            viewport_width: 640.75,
            viewport_height: 480.5,
            viewport_dpr: 1.5,
            ..Event::default()
        },
        Event {
            kind: 13,
            target: 2,
            pointer_phase: 1,
            pointer_device: 2,
            pointer_x: 123.75,
            pointer_y: 222.5,
            bounded_drops: 2,
            ..Event::default()
        },
        Event {
            kind: 13,
            target: 3,
            pointer_x: 210.25,
            pointer_y: 111.75,
            bounded_drops: 3,
            ..Event::default()
        },
        Event {
            kind: 13,
            target: 5,
            document_hidden: true,
            ..Event::default()
        },
        Event {
            kind: 13,
            target: 5,
            document_hidden: false,
            ..Event::default()
        },
        Event {
            kind: 13,
            target: 7,
            bounded_drops: 0,
            latest_value: 4,
            ..Event::default()
        },
        Event {
            kind: 13,
            target: 6,
            frame_timestamp: 456.75,
            ..Event::default()
        },
        Event {
            kind: 13,
            target: 4,
            ..Event::default()
        },
        Event {
            kind: 1,
            ..Event::default()
        },
        Event {
            kind: 13,
            target: 2,
            pointer_x: 999.0,
            pointer_y: 999.0,
            ..Event::default()
        },
    ];

    for (index, event) in tape.into_iter().enumerate() {
        expected = reduce(expected, event);
        let mut output = vec![wasmtime::Val::I32(0); STATE_LEAVES];
        transition
            .call(&mut store, &event_values(event), &mut output)
            .unwrap_or_else(|error| panic!("Event Studio event {index} trapped: {error}"));
        assert_eq!(
            state_values(&output),
            expected,
            "state drift at event {index}"
        );
    }

    let invalid = Event {
        kind: 13,
        target: 99,
        ..tape[0]
    };
    let mut output = vec![wasmtime::Val::I32(0); STATE_LEAVES];
    assert!(
        transition
            .call(&mut store, &event_values(invalid), &mut output)
            .is_err(),
        "invalid compiler-derived action tags must trap before Fe observes them"
    );

    let invalid_pointer_phase = Event {
        kind: 13,
        target: 2,
        pointer_phase: 99,
        ..tape[3]
    };
    assert!(
        transition
            .call(
                &mut store,
                &event_values(invalid_pointer_phase),
                &mut output,
            )
            .is_err(),
        "invalid nested PointerPhase tags must trap at the generated boundary"
    );
}
