//! Executable semantic gate for the configured-provider sparse metric path.
//!
//! The Fe provider reflects `using CompileVectorScalarF32<GaProgram<...>>`,
//! emits the scalar product, and leaves the runtime carrier free of phantom
//! program fields. This oracle is independently tabled from the Fe metric type.

use common::InputDb;
use driver::DriverDataBase;
use fe_codegen::{BackendKind, OptLevel, layout_for};
use hir::hir_def::HirIngot;
use std::path::Path;
use url::Url;
use wasmtime::Val;

fn expected(p: [f32; 12], q: [f32; 12]) -> f32 {
    // Match the documented AlgebraicBalanced four-term chunk topology. The
    // order follows the sparse metric entries and their applicable symmetric
    // orientations; it is not copied from generated bytes.
    let terms = [
        p[0] * q[0],
        p[1] * q[1],
        p[2] * q[2],
        -(p[3] * q[9]),
        -(p[6] * q[3]),
        -(p[4] * q[10]),
        -(p[7] * q[4]),
        -(p[5] * q[11]),
        -(p[8] * q[5]),
        -(p[9] * q[6]),
        -(p[10] * q[7]),
        -(p[11] * q[8]),
    ];
    let zero = 0.0;
    let mut chunks = [zero; 3];
    for (index, term) in terms.into_iter().enumerate() {
        chunks[index / 4] += term;
    }
    (chunks[0] + chunks[1]) + chunks[2]
}

fn tiny_expected(l: [f32; 3], r: [f32; 3]) -> f32 {
    let zero = 0.0;
    let twice_l0r0 = l[0] * r[0] + l[0] * r[0];
    let negative_l1r3 = -(l[1] * r[2]);
    let l2r2 = l[2] * r[1];
    let negative_thrice_l2r2 = -((l2r2 + l2r2) + l2r2);
    (((zero + twice_l0r0) + negative_l1r3) + negative_thrice_l2r2) + zero + zero
}

#[test]
fn configured_sparse_symmetric_metric_executes_without_host_algebra() {
    let path =
        Path::new(env!("CARGO_MANIFEST_DIR")).join("tests/fixtures/ga_expr_sparse_metric_fco");
    let url = Url::from_directory_path(path.canonicalize().unwrap()).unwrap();
    let mut db = DriverDataBase::default();
    assert!(!driver::init_ingot(&mut db, &url));
    let ingot = db.workspace().containing_ingot(&db, url).unwrap();
    let top_mod = ingot.root_mod(&db);
    let diagnostics = db.run_on_top_mod(top_mod).format_diags(&db);
    assert!(
        diagnostics.is_empty(),
        "sparse metric diagnostics:\n{diagnostics}"
    );

    let wasm = BackendKind::Wasm
        .create()
        .compile(&db, top_mod, layout_for(BackendKind::Wasm), OptLevel::O0)
        .expect("sparse metric fixture compiles to Wasm")
        .into_bytecode()
        .expect("Wasm backend returns bytecode");
    wasmparser::validate(&wasm).expect("sparse metric Wasm validates");
    let engine = wasmtime::Engine::default();
    let module = wasmtime::Module::new(&engine, &wasm).unwrap();
    assert!(
        module.imports().next().is_none(),
        "no host GA implementation"
    );
    let mut store = wasmtime::Store::new(&engine, ());
    let instance = wasmtime::Instance::new(&mut store, &module, &[]).unwrap();
    let function = instance
        .get_func(&mut store, "sparse_metric_probe")
        .expect("exported sparse metric probe");
    let tiny = instance
        .get_typed_func::<(f32, f32, f32, f32, f32, f32), f32>(&mut store, "tiny_metric_probe")
        .expect("differently configured sparse metric probe");
    let reversed_tiny = instance
        .get_typed_func::<(f32, f32, f32, f32, f32, f32), f32>(
            &mut store,
            "reversed_tiny_metric_probe",
        )
        .expect("reversed expression probe");
    let auto_null = instance
        .get_typed_func::<(f32, f32, f32, f32, f32, f32), f32>(&mut store, "auto_null_metric_probe")
        .expect("automatically paired null-basis probe");
    let matrix_null = instance
        .get_typed_func::<(f32, f32, f32, f32, f32, f32), f32>(
            &mut store,
            "matrix_null_metric_probe",
        )
        .expect("named symmetric-matrix probe");

    let mut cases = vec![
        ([0.0; 12], [0.0; 12]),
        ([1.0; 12], [1.0; 12]),
        (
            [
                1.0, -2.0, 3.0, 4.0, -5.0, 6.0, 7.0, -8.0, 9.0, 10.0, -11.0, 12.0,
            ],
            [
                -0.5, 1.5, 2.5, -3.5, 4.5, -5.5, 6.5, -7.5, 8.5, -9.5, 10.5, -11.5,
            ],
        ),
    ];
    let mut state = 0x97a2_4f31_u32;
    let mut next = || {
        state = state.wrapping_mul(1_664_525).wrapping_add(1_013_904_223);
        ((state >> 10) as i32 as f32) / 8_192.0 - 256.0
    };
    for _ in 0..256 {
        cases.push((
            std::array::from_fn(|_| next()),
            std::array::from_fn(|_| next()),
        ));
    }

    for (p, q) in cases {
        let params: Vec<Val> = p
            .into_iter()
            .chain(q)
            .map(|value| Val::F32(value.to_bits()))
            .collect();
        let mut results = [Val::F32(0)];
        function.call(&mut store, &params, &mut results).unwrap();
        let Val::F32(bits) = results[0] else {
            unreachable!()
        };
        assert_eq!(
            bits,
            expected(p, q).to_bits(),
            "configured sparse metric schedule drifted for p={p:?}, q={q:?}"
        );
    }

    let mut tiny_cases = vec![
        ([0.0; 3], [0.0; 3]),
        ([1.0, 2.0, 3.0], [4.0, 5.0, 6.0]),
        ([-0.0, -7.5, 0.25], [3.0, -4.5, 8.0]),
    ];
    for _ in 0..128 {
        tiny_cases.push(([next(), next(), next()], [next(), next(), next()]));
    }
    for (l, r) in tiny_cases {
        let args = (l[0], l[1], l[2], r[0], r[1], r[2]);
        let wanted = tiny_expected(l, r).to_bits();
        assert_eq!(
            tiny.call(&mut store, args).unwrap().to_bits(),
            wanted,
            "metric/support substitution drifted for l={l:?}, r={r:?}",
        );
        assert_eq!(
            reversed_tiny.call(&mut store, args).unwrap().to_bits(),
            wanted,
            "expression operand-order substitution drifted for l={l:?}, r={r:?}",
        );
    }

    let mut null_cases = vec![
        ([0.0; 3], [0.0; 3]),
        ([1.0, 2.0, 3.0], [4.0, 5.0, 6.0]),
        ([-0.0, -7.5, 0.25], [3.0, -4.5, 8.0]),
    ];
    for _ in 0..128 {
        null_cases.push(([next(), next(), next()], [next(), next(), next()]));
    }
    for (left, right) in null_cases {
        // Basis order is x, origin, infinity. This oracle is independent of
        // both Fe descriptor forms and of their reflected field order.
        let zero = 0.0;
        let expected =
            (((zero + left[0] * right[0]) - left[1] * right[2]) - left[2] * right[1]) + zero + zero;
        let args = (left[0], left[1], left[2], right[0], right[1], right[2]);
        assert_eq!(
            auto_null.call(&mut store, args).unwrap().to_bits(),
            expected.to_bits(),
            "automatic null pairing drifted for left={left:?}, right={right:?}",
        );
        assert_eq!(
            matrix_null.call(&mut store, args).unwrap().to_bits(),
            expected.to_bits(),
            "named matrix metric drifted for left={left:?}, right={right:?}",
        );
    }
}
