//! Semantic and emitted-shape gate for the structural GA-expression provider.
//!
//! The same provider lowers two different trees. Rust interprets those trees
//! independently; generated byte shape is only a performance gate, never the
//! correctness oracle.

use common::InputDb;
use driver::DriverDataBase;
use fe_codegen::{BackendKind, OptLevel, compile_runtime_package_spirv_render, layout_for};
use hir::hir_def::HirIngot;
use std::path::Path;
use url::Url;

fn wedge(l: [f32; 3], r: [f32; 3]) -> [f32; 3] {
    [
        l[0] * r[1] + -(l[1] * r[0]),
        l[0] * r[2] + -(l[2] * r[0]),
        l[1] * r[2] + -(l[2] * r[1]),
    ]
}

fn repeated_tree(l: [f32; 3], r: [f32; 3]) -> [f32; 3] {
    // Interpret the authored tree, including its strict association:
    // `(a ^ b) + (a ^ b)`.
    let first = wedge(l, r);
    let second = wedge(l, r);
    [
        first[0] + second[0],
        first[1] + second[1],
        first[2] + second[2],
    ]
}

fn distributed_tree(l: [f32; 3], r: [f32; 3]) -> [f32; 3] {
    // Interpret the structurally different authored tree:
    // `-((a + b) ^ (a - b))`.
    let sum = [l[0] + r[0], l[1] + r[1], l[2] + r[2]];
    let difference = [l[0] - r[0], l[1] - r[1], l[2] - r[2]];
    let product = wedge(sum, difference);
    [-product[0], -product[1], -product[2]]
}

#[test]
fn one_provider_lowers_distinct_ga_trees_to_semantic_wasm_and_branch_free_wgsl() {
    let path = Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("tests/fixtures/ga_expr_operator_substitution_fco");
    let url = Url::from_directory_path(path.canonicalize().unwrap()).unwrap();
    let mut db = DriverDataBase::default();
    assert!(
        !driver::init_ingot(&mut db, &url),
        "structural GA fixture initialization diagnostics"
    );
    let ingot = db
        .workspace()
        .containing_ingot(&db, url)
        .expect("structural GA fixture ingot");
    let top_mod = ingot.root_mod(&db);
    let diagnostics = db.run_on_top_mod(top_mod).format_diags(&db);
    assert!(
        diagnostics.is_empty(),
        "structural GA fixture diagnostics:\n{diagnostics}"
    );

    let wasm = BackendKind::Wasm
        .create()
        .compile(&db, top_mod, layout_for(BackendKind::Wasm), OptLevel::O0)
        .expect("structural GA fixture compiles to Wasm")
        .into_bytecode()
        .expect("Wasm backend returns bytecode");
    wasmparser::validate(&wasm).expect("structural GA Wasm validates");
    let engine = wasmtime::Engine::default();
    let module = wasmtime::Module::new(&engine, &wasm).unwrap();
    assert!(
        module.imports().next().is_none(),
        "the structural evaluator must not import a host algebra implementation"
    );
    let mut store = wasmtime::Store::new(&engine, ());
    let instance = wasmtime::Instance::new(&mut store, &module, &[]).unwrap();
    let component = |name: &str, store: &mut wasmtime::Store<()>| {
        instance
            .get_typed_func::<(f32, f32, f32, f32, f32, f32), f32>(&mut *store, name)
            .unwrap_or_else(|error| panic!("missing/mistyped `{name}`: {error}"))
    };
    let repeated = [
        component("repeated_c3", &mut store),
        component("repeated_c5", &mut store),
        component("repeated_c6", &mut store),
    ];
    let distributed = [
        component("distributed_c3", &mut store),
        component("distributed_c5", &mut store),
        component("distributed_c6", &mut store),
    ];

    let mut cases = vec![
        ([1.0, 0.0, 0.0], [0.0, 1.0, 0.0]),
        ([2.0, -3.0, 0.5], [0.25, 4.0, -1.5]),
        ([-0.0, 1.0, -2.0], [0.0, -3.0, 4.0]),
        ([0.0; 3], [0.0; 3]),
    ];
    let mut state = 0x6b71_932d_u32;
    let mut next = || {
        state = state.wrapping_mul(1_664_525).wrapping_add(1_013_904_223);
        ((state >> 9) as i32 as f32) / 16_384.0 - 512.0
    };
    for _ in 0..1_000 {
        cases.push(([next(), next(), next()], [next(), next(), next()]));
    }

    for (l, r) in cases {
        let args = (l[0], l[1], l[2], r[0], r[1], r[2]);
        let got_repeated = [
            repeated[0].call(&mut store, args).unwrap(),
            repeated[1].call(&mut store, args).unwrap(),
            repeated[2].call(&mut store, args).unwrap(),
        ];
        let got_distributed = [
            distributed[0].call(&mut store, args).unwrap(),
            distributed[1].call(&mut store, args).unwrap(),
            distributed[2].call(&mut store, args).unwrap(),
        ];
        assert_eq!(
            got_repeated.map(f32::to_bits),
            repeated_tree(l, r).map(f32::to_bits),
            "structural provider changed repeated-tree semantics for l={l:?}, r={r:?}"
        );
        assert_eq!(
            got_distributed.map(f32::to_bits),
            distributed_tree(l, r).map(f32::to_bits),
            "structural provider changed distributed-tree semantics for l={l:?}, r={r:?}"
        );
    }

    let package = mir::build_wasm_runtime_package_for_entry(&db, top_mod, "structural_ga_render")
        .expect("structural GA render runtime package");
    let artifact = compile_runtime_package_spirv_render(&db, &package)
        .expect("structural GA expression compiles through render SPIR-V");
    assert_eq!(artifact.words.first().copied(), Some(0x0723_0203));
    let wgsl = artifact.wgsl.expect("structural GA browser WGSL");
    let module = naga::front::wgsl::parse_str(&wgsl).expect("structural GA WGSL reparses");
    naga::valid::Validator::new(
        naga::valid::ValidationFlags::all(),
        naga::valid::Capabilities::default(),
    )
    .validate(&module)
    .expect("structural GA WGSL validates with browser-default capabilities");
    assert!(
        !wgsl.contains("loop {") && !wgsl.contains("if (") && !wgsl.contains("switch"),
        "compile-time structural planning must leave no runtime control flow:\n{wgsl}"
    );
}
