//! Independent semantic gate for the shared Fe ordered sampling construction.
//!
//! This compiles and executes the real `fmath::PixelSample` implementation in
//! Wasm. The oracle derives the geometry independently: every integer pixel
//! contains its sample, the four samples of an aligned 2x2 block occupy all
//! four subpixel quadrants, their offsets have centroid `(1/2, 1/2)`, and the
//! normalized plane mapping has the requested orientation. Generated bytes are
//! not compared and are not treated as behavioral evidence.

use std::path::Path;

use common::InputDb;
use driver::DriverDataBase;
use fe_codegen::{BackendKind, OptLevel, layout_for};
use hir::hir_def::HirIngot;
use url::Url;

fn compile_gate() -> Vec<u8> {
    let path =
        Path::new(env!("CARGO_MANIFEST_DIR")).join("tests/fixtures/refined_sampling_oracle_ingot");
    let url = Url::from_directory_path(path.canonicalize().unwrap()).unwrap();
    let mut db = DriverDataBase::default();
    assert!(
        !driver::init_ingot(&mut db, &url),
        "refined-sampling gate ingot initialization diagnostics"
    );
    let ingot = db
        .workspace()
        .containing_ingot(&db, url)
        .expect("refined-sampling gate ingot");
    let top_mod = ingot.root_mod(&db);
    let diagnostics = db.run_on_top_mod(top_mod).format_diags(&db);
    assert!(
        diagnostics.is_empty(),
        "unexpected refined-sampling diagnostics:\n{diagnostics}"
    );
    let wasm = BackendKind::Wasm
        .create()
        .compile(&db, top_mod, layout_for(BackendKind::Wasm), OptLevel::O0)
        .expect("refined-sampling gate should compile to Wasm")
        .into_bytecode()
        .expect("Wasm output should be bytecode");
    wasmparser::validate(&wasm).expect("refined-sampling Wasm should validate");
    wasm
}

fn expected_offset(coordinate: i32) -> f32 {
    if coordinate % 2 == 0 {
        3.0 / 8.0
    } else {
        5.0 / 8.0
    }
}

#[test]
fn ordered_sampling_executes_with_stratified_centroid_and_plane_orientation() {
    let wasm = compile_gate();
    let engine = wasmtime::Engine::default();
    let module = wasmtime::Module::new(&engine, &wasm).expect("load sampling Wasm");
    assert!(
        module.imports().next().is_none(),
        "the sampling gate must be self-contained"
    );
    let mut store = wasmtime::Store::new(&engine, ());
    let instance =
        wasmtime::Instance::new(&mut store, &module, &[]).expect("instantiate sampling Wasm");
    let sample_x = instance
        .get_typed_func::<(i32, i32), f32>(&mut store, "ordered_sample_x")
        .expect("ordered_sample_x export");
    let sample_y = instance
        .get_typed_func::<(i32, i32), f32>(&mut store, "ordered_sample_y")
        .expect("ordered_sample_y export");
    let plane_u = instance
        .get_typed_func::<(i32, i32, f32), f32>(&mut store, "ordered_plane_u")
        .expect("ordered_plane_u export");
    let plane_v = instance
        .get_typed_func::<(i32, i32, f32), f32>(&mut store, "ordered_plane_v")
        .expect("ordered_plane_v export");

    for py in 0..16 {
        for px in 0..16 {
            let x = sample_x.call(&mut store, (px, py)).expect("sample x");
            let y = sample_y.call(&mut store, (px, py)).expect("sample y");
            assert!(x > px as f32 && x < (px + 1) as f32);
            assert!(y > py as f32 && y < (py + 1) as f32);
            assert_eq!(x - px as f32, expected_offset(px));
            assert_eq!(y - py as f32, expected_offset(py));

            let resolution = 16.0f32;
            let u = plane_u
                .call(&mut store, (px, py, resolution))
                .expect("plane u");
            let v = plane_v
                .call(&mut store, (px, py, resolution))
                .expect("plane v");
            let expected_u = x / resolution * 2.0 - 1.0;
            let expected_v = 1.0 - y / resolution * 2.0;
            assert!((u - expected_u).abs() <= f32::EPSILON);
            assert!((v - expected_v).abs() <= f32::EPSILON);
        }
    }

    for block_y in (0..16).step_by(2) {
        for block_x in (0..16).step_by(2) {
            let mut offsets = Vec::new();
            for dy in 0..2 {
                for dx in 0..2 {
                    let px = block_x + dx;
                    let py = block_y + dy;
                    let x = sample_x.call(&mut store, (px, py)).unwrap();
                    let y = sample_y.call(&mut store, (px, py)).unwrap();
                    offsets.push((x - px as f32, y - py as f32));
                }
            }
            offsets.sort_by_key(|(x, y)| (x.to_bits(), y.to_bits()));
            assert_eq!(
                offsets,
                [
                    (0.375, 0.375),
                    (0.375, 0.625),
                    (0.625, 0.375),
                    (0.625, 0.625)
                ]
            );
            let centroid_x = offsets.iter().map(|sample| sample.0).sum::<f32>() / 4.0;
            let centroid_y = offsets.iter().map(|sample| sample.1).sum::<f32>() / 4.0;
            assert_eq!((centroid_x, centroid_y), (0.5, 0.5));
        }
    }
}
