//! Independent semantic gate for Fe-owned Source Atlas navigation.
//!
//! Wasmtime executes the Fe reducer. The assertions specify navigation and
//! concurrency behavior independently of the generated bytes.

use std::path::Path;

use common::InputDb;
use driver::DriverDataBase;
use fe_codegen::{BackendKind, OptLevel, layout_for};
use hir::hir_def::HirIngot;
use url::Url;

fn compile_atlas_navigation() -> Vec<u8> {
    let path =
        Path::new(env!("CARGO_MANIFEST_DIR")).join("tests/fixtures/source_atlas_navigation_ingot");
    let url = Url::from_directory_path(path.canonicalize().unwrap()).unwrap();
    let mut db = DriverDataBase::default();
    assert!(!driver::init_ingot(&mut db, &url));
    let ingot = db.workspace().containing_ingot(&db, url).unwrap();
    let top_mod = ingot.root_mod(&db);
    let diagnostics = db.run_on_top_mod(top_mod).format_diags(&db);
    assert!(
        diagnostics.is_empty(),
        "Source Atlas navigation fixture diagnostics:\n{diagnostics}"
    );
    let wasm = BackendKind::Wasm
        .create()
        .compile(&db, top_mod, layout_for(BackendKind::Wasm), OptLevel::O0)
        .expect("Fe Source Atlas navigation should compile to Wasm")
        .into_bytecode()
        .expect("Wasm bytes");
    wasmparser::validate(&wasm).expect("Source Atlas navigation Wasm should validate");
    wasm
}

#[test]
fn fe_owns_navigation_history_stale_queries_and_semantic_highlights() {
    let wasm = compile_atlas_navigation();
    let engine = wasmtime::Engine::default();
    let module = wasmtime::Module::new(&engine, wasm).unwrap();
    let mut store = wasmtime::Store::new(&engine, ());
    let instance = wasmtime::Instance::new(&mut store, &module, &[]).unwrap();

    let call = |store: &mut wasmtime::Store<()>, name: &str| {
        instance
            .get_typed_func::<(), i32>(&mut *store, name)
            .unwrap()
            .call(store, ())
            .unwrap()
    };

    assert_eq!(call(&mut store, "history_branch_probe"), 32_042);
    assert_eq!(call(&mut store, "history_capacity_probe"), 30_021);
    assert_eq!(call(&mut store, "stale_completion_probe"), 11);
    assert_eq!(call(&mut store, "independent_revision_probe"), 7);
    assert_eq!(call(&mut store, "semantic_highlight_probe"), 15);
    assert_eq!(call(&mut store, "range_boundary_probe"), 6);
}
