//! Independent executable oracle for the production Fe UTF-8/text substrate.
//!
//! Fe performs every decode, relation, bounded mutation, literal copy, and
//! FCO layout operation. Rust supplies adversarial bytes and compares semantic
//! values against its standard UTF-8 implementation; generated byte equality
//! is deliberately not used as a correctness claim.

use common::InputDb;
use driver::DriverDataBase;
use fe_codegen::{WasmCompileOptions, compile_runtime_package_wasm_with_options};
use hir::hir_def::HirIngot;
use url::Url;

fn compile_gate() -> Vec<u8> {
    let path = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("tests/fixtures/text_utf8_oracle_ingot");
    let url = Url::from_directory_path(path.canonicalize().unwrap()).unwrap();
    let mut db = DriverDataBase::default();
    assert!(!driver::init_ingot(&mut db, &url), "ingot diagnostics");
    let ingot = db
        .workspace()
        .containing_ingot(&db, url)
        .expect("text oracle ingot");
    let top_mod = ingot.root_mod(&db);
    let diagnostics = db.run_on_top_mod(top_mod).format_diags(&db);
    assert!(
        diagnostics.is_empty(),
        "unexpected text-oracle diagnostics:\n{diagnostics}"
    );
    let package = mir::build_wasm_runtime_package(&db, top_mod)
        .expect("text oracle should build a runtime package");
    compile_runtime_package_wasm_with_options(&db, &package, WasmCompileOptions::default())
        .expect("text oracle should compile to Wasm")
        .bytes
}

fn fnv1a(bytes: &[u8]) -> u32 {
    bytes.iter().fold(2_166_136_261_u32, |state, byte| {
        (state ^ u32::from(*byte)).wrapping_mul(16_777_619)
    })
}

fn view_receipt(bytes: &[u8]) -> u64 {
    ((bytes.len() as u64) << 32) | u64::from(fnv1a(bytes))
}

fn write_receipt(len: usize, truncated: bool, valid: bool) -> u32 {
    len as u32 | (u32::from(truncated) << 16) | (u32::from(valid) << 17)
}

fn bounded_prefix(value: &str, capacity: usize) -> &str {
    let mut end = value.len().min(capacity);
    while !value.is_char_boundary(end) {
        end -= 1;
    }
    &value[..end]
}

#[test]
fn fe_utf8_text_operations_execute_against_independent_semantics() {
    let wasm = compile_gate();
    wasmparser::validate(&wasm).expect("text oracle Wasm validates");
    let engine = wasmtime::Engine::default();
    let module = wasmtime::Module::new(&engine, &wasm).expect("text oracle module");
    assert!(
        module.imports().next().is_none(),
        "text oracle is zero-import"
    );
    let mut store = wasmtime::Store::new(&engine, ());
    let instance = wasmtime::Instance::new(&mut store, &module, &[]).unwrap();
    let memory = instance.get_memory(&mut store, "memory").unwrap();

    let valid = instance
        .get_typed_func::<(i32, i32), i32>(&mut store, "utf8_valid")
        .unwrap();
    let char_count = instance
        .get_typed_func::<(i32, i32), i32>(&mut store, "utf8_char_count")
        .unwrap();
    let boundary = instance
        .get_typed_func::<(i32, i32, i32), i32>(&mut store, "utf8_boundary")
        .unwrap();
    let decode = instance
        .get_typed_func::<(i32, i32, i32), i64>(&mut store, "utf8_decode")
        .unwrap();
    let prefix = instance
        .get_typed_func::<(i32, i32, i32), i64>(&mut store, "utf8_prefix")
        .unwrap();
    let slice = instance
        .get_typed_func::<(i32, i32, i32, i32), i64>(&mut store, "utf8_slice")
        .unwrap();
    let relations = instance
        .get_typed_func::<(i32, i32, i32, i32), i32>(&mut store, "utf8_relations")
        .unwrap();
    let replace = instance
        .get_typed_func::<(i32, i32, i32, i32), i32>(&mut store, "utf8_replace")
        .unwrap();
    let append = instance
        .get_typed_func::<(i32, i32, i32, i32, i32), i32>(&mut store, "utf8_append")
        .unwrap();
    let literal = instance
        .get_typed_func::<(i32, i32), i32>(&mut store, "utf8_literal")
        .unwrap();
    let literal4 = instance
        .get_typed_func::<(i32, i32, i32, i32, i32, i32), i32>(&mut store, "utf8_literal4")
        .unwrap();
    let layout = instance
        .get_typed_func::<i32, i64>(&mut store, "text_layout_receipt")
        .unwrap();

    const INPUT: usize = 4_096;
    const OTHER: usize = 8_192;
    const OUTPUT: usize = 12_288;
    let sample = "A¢ह🌍z";
    memory.write(&mut store, INPUT, sample.as_bytes()).unwrap();

    assert_eq!(
        valid
            .call(&mut store, (INPUT as i32, sample.len() as i32))
            .unwrap(),
        1
    );
    assert_eq!(
        char_count
            .call(&mut store, (INPUT as i32, sample.len() as i32))
            .unwrap(),
        sample.chars().count() as i32
    );
    for index in 0..=sample.len() {
        assert_eq!(
            boundary
                .call(
                    &mut store,
                    (INPUT as i32, sample.len() as i32, index as i32),
                )
                .unwrap(),
            i32::from(sample.is_char_boundary(index)),
            "boundary {index}"
        );
    }

    for (index, scalar) in sample.char_indices() {
        let raw = decode
            .call(
                &mut store,
                (INPUT as i32, sample.len() as i32, index as i32),
            )
            .unwrap() as u64;
        assert_eq!(raw >> 63, 1, "decode validity at {index}");
        assert_eq!(raw as u32, scalar as u32, "scalar at {index}");
        assert_eq!(
            (raw >> 32) as u32 & 0x7fff_ffff,
            (index + scalar.len_utf8()) as u32
        );
    }

    for capacity in 0..=sample.len() {
        let expected = bounded_prefix(sample, capacity);
        assert_eq!(
            prefix
                .call(
                    &mut store,
                    (INPUT as i32, sample.len() as i32, capacity as i32),
                )
                .unwrap() as u64,
            view_receipt(expected.as_bytes()),
            "prefix capacity {capacity}"
        );
    }

    let earth_start = sample.find('🌍').unwrap();
    let earth_end = earth_start + '🌍'.len_utf8();
    assert_eq!(
        slice
            .call(
                &mut store,
                (
                    INPUT as i32,
                    sample.len() as i32,
                    earth_start as i32,
                    earth_end as i32,
                ),
            )
            .unwrap() as u64,
        (1_u64 << 63) | view_receipt("🌍".as_bytes())
    );
    assert_eq!(
        slice
            .call(
                &mut store,
                (
                    INPUT as i32,
                    sample.len() as i32,
                    earth_start as i32 + 1,
                    earth_end as i32
                ),
            )
            .unwrap(),
        0,
        "a continuation-byte slice boundary is rejected"
    );

    let needle = "ह🌍";
    memory.write(&mut store, OTHER, needle.as_bytes()).unwrap();
    assert_eq!(
        relations
            .call(
                &mut store,
                (
                    INPUT as i32,
                    sample.len() as i32,
                    OTHER as i32,
                    needle.len() as i32
                ),
            )
            .unwrap(),
        8 | 16,
        "sample contains the needle and sorts before it"
    );
    assert_eq!(
        relations
            .call(
                &mut store,
                (
                    INPUT as i32,
                    sample.len() as i32,
                    INPUT as i32,
                    sample.len() as i32
                ),
            )
            .unwrap(),
        1 | 2 | 4 | 8 | 32
    );

    let malformed: &[&[u8]] = &[
        &[0x80],
        &[0xc0, 0x80],
        &[0xe0, 0x80, 0x80],
        &[0xed, 0xa0, 0x80],
        &[0xf4, 0x90, 0x80, 0x80],
        &[0xf0, 0x9f],
    ];
    for bytes in malformed {
        memory.write(&mut store, OTHER, bytes).unwrap();
        assert_eq!(
            valid
                .call(&mut store, (OTHER as i32, bytes.len() as i32))
                .unwrap(),
            0,
            "malformed bytes {bytes:x?}"
        );
    }

    let boundary_title = format!("{}🌍", "a".repeat(95));
    memory
        .write(&mut store, OTHER, boundary_title.as_bytes())
        .unwrap();
    assert_eq!(
        replace
            .call(
                &mut store,
                (OUTPUT as i32, 96, OTHER as i32, boundary_title.len() as i32),
            )
            .unwrap() as u32,
        write_receipt(95, true, true)
    );
    let mut copied = vec![0; 95];
    memory.read(&mut store, OUTPUT, &mut copied).unwrap();
    assert_eq!(std::str::from_utf8(&copied).unwrap(), "a".repeat(95));

    memory.write(&mut store, OUTPUT, "A¢".as_bytes()).unwrap();
    assert_eq!(
        append
            .call(&mut store, (OUTPUT as i32, 3, 8, INPUT as i32 + 3, 7),)
            .unwrap() as u32,
        write_receipt(6, true, true),
        "append keeps the complete Devanagari scalar and not a partial globe"
    );
    let mut appended = vec![0; 6];
    memory.read(&mut store, OUTPUT, &mut appended).unwrap();
    assert_eq!(std::str::from_utf8(&appended).unwrap(), "A¢ह");

    assert_eq!(
        literal.call(&mut store, (OUTPUT as i32, 10)).unwrap() as u32,
        write_receipt(10, true, true)
    );
    let expected_literal = bounded_prefix(sample, 10).as_bytes();
    let mut literal_bytes = vec![0; expected_literal.len()];
    memory.read(&mut store, OUTPUT, &mut literal_bytes).unwrap();
    assert_eq!(literal_bytes, expected_literal);

    assert_eq!(
        literal4
            .call(&mut store, (OUTPUT as i32, 2, 0xf0, 0x9f, 0x8c, 0x8d),)
            .unwrap() as u32,
        write_receipt(0, true, true),
        "capacity truncation never turns valid source UTF-8 into an invalid write"
    );
    assert_eq!(
        literal4
            .call(&mut store, (OUTPUT as i32, 4, 0xf0, 0x28, 0x8c, 0x28),)
            .unwrap() as u32,
        write_receipt(0, true, false),
        "an arbitrary malformed byte array is rejected independently of capacity"
    );

    assert_eq!(
        layout.call(&mut store, OUTPUT as i32).unwrap() as u64,
        (34_u64 << 32) | (27_u64 << 16),
        "FCO derives first=0, rows[2]=27, and last=34"
    );
}
