//! Executable browser gate for Fe-owned structured-child orchestration.
//!
//! The fixed host supplies only spawn, runtime-failure observation, timer, and
//! close mechanics. Actual Fe Wasm owns epochs, restart admission, backoff,
//! exhaustion, transport failure, and parent-cancellation cleanup. Assertions
//! inspect semantic call tapes and Fe-selected results, never generated bytes.

use common::InputDb;
use driver::DriverDataBase;
use fe_codegen::{
    HOST_COMPLETION_RUNTIME_JS, MATERIALIZED_TASK_RUNTIME_JS, WasmCompileOptions,
    compile_runtime_package_wasm_with_options, emit_materialized_task_adapter_js,
    materialized_task_adapters,
};
use url::Url;

#[test]
fn compiled_fe_scope_owns_restart_exhaustion_transport_failure_and_cancellation() {
    const SOURCE: &str = r#"
use std::runtime::{ChildFailureKind, ChildScopeExit, supervise_browser_child}

pub struct OracleChild {}

pub fn scope_task() -> u64 {
    let exit = supervise_browser_child(
        child: OracleChild {},
        max_restarts: 2,
        window_ms: 1000,
        backoff_ms: 0,
    )
    match exit {
        ChildScopeExit::Cancelled(epoch) => 10000 + epoch as u64
        ChildScopeExit::Exhausted(epoch, failure) => {
            match failure {
                ChildFailureKind::None => 90000 + epoch as u64
                ChildFailureKind::Startup => 1000 + epoch as u64
                ChildFailureKind::Runtime => 2000 + epoch as u64
            }
        }
        ChildScopeExit::TransportFailure(epoch, error) => {
            300000 + epoch as u64 * 100 + error as u64
        }
        ChildScopeExit::InvariantViolation(epoch, _) => 400000 + epoch as u64
    }
}
"#;

    if !std::process::Command::new("bun")
        .arg("--version")
        .output()
        .is_ok_and(|output| output.status.success())
    {
        return;
    }

    let mut db = DriverDataBase::default();
    let url = Url::parse("file:///worker_scope_runtime.fe").unwrap();
    db.workspace()
        .touch(&mut db, url.clone(), Some(SOURCE.to_owned()));
    let file = db.workspace().get(&db, &url).unwrap();
    let top_mod = db.top_mod(file);
    let diagnostics = db.run_on_top_mod(top_mod).format_diags(&db);
    assert!(
        diagnostics.is_empty(),
        "structured Worker scope diagnostics:\n{diagnostics}"
    );

    let package = mir::build_wasm_runtime_package_for_entry(&db, top_mod, "scope_task")
        .expect("Fe scope should materialize through the resumable MIR rail");
    let adapters = materialized_task_adapters(&db, &package).unwrap();
    assert_eq!(adapters.len(), 1);
    assert_eq!(adapters[0].name, "scope_task");
    assert!(adapters[0].continuations.len() >= 3);
    let adapter = emit_materialized_task_adapter_js(&adapters, "./materialized-task.js")
        .unwrap()
        .expect("Fe scope should publish one compiler-derived task adapter");
    let wasm =
        compile_runtime_package_wasm_with_options(&db, &package, WasmCompileOptions::default())
            .unwrap()
            .bytes;
    wasmparser::validate(&wasm).unwrap();

    let imports = wasmparser::Parser::new(0)
        .parse_all(&wasm)
        .filter_map(|payload| match payload.unwrap() {
            wasmparser::Payload::ImportSection(section) => Some(
                section
                    .into_imports()
                    .map(|import| {
                        let import = import.unwrap();
                        (import.module.to_owned(), import.name.to_owned())
                    })
                    .collect::<Vec<_>>(),
            ),
            _ => None,
        })
        .flatten()
        .collect::<std::collections::BTreeSet<_>>();
    for name in ["spawn_begin", "failure_begin", "close"] {
        assert!(
            imports.contains(&("fe:worker-scope".to_owned(), name.to_owned())),
            "compiled Fe scope is missing fe:worker-scope::{name}: {imports:?}"
        );
    }
    assert!(
        imports.contains(&("fe:host".to_owned(), "sleep_begin".to_owned())),
        "Fe backoff must use the ordinary timer effect: {imports:?}"
    );
    assert!(!imports.iter().any(|(_, name)| name == "wait"));

    let directory = tempfile::tempdir().unwrap();
    let wasm_path = directory.path().join("worker-scope.wasm");
    let task_runtime_path = directory.path().join("materialized-task.js");
    let host_runtime_path = directory.path().join("host-completion.js");
    let adapter_path = directory.path().join("task-adapter.mjs");
    let test_path = directory.path().join("worker-scope-browser.mjs");
    std::fs::write(&wasm_path, wasm).unwrap();
    std::fs::write(&task_runtime_path, MATERIALIZED_TASK_RUNTIME_JS).unwrap();
    std::fs::write(&host_runtime_path, HOST_COMPLETION_RUNTIME_JS).unwrap();
    std::fs::write(&adapter_path, adapter).unwrap();

    let script = format!(
        r#"
import {{ createMaterializedTaskRegistry }} from {adapter_url:?};
import {{ createHostCompletionBroker }} from {host_runtime_url:?};
const bytes = await Bun.file({wasm_path:?}).arrayBuffer();

async function instantiate(workerScope) {{
  const broker = createHostCompletionBroker({{ workerScope }});
  const {{ instance }} = await WebAssembly.instantiate(bytes, broker.imports);
  return {{ broker, task: createMaterializedTaskRegistry(instance.exports).scope_task }};
}}

// One runtime failure and two startup failures consume exactly Fe's two-restart
// budget. The host never chooses or schedules an extra spawn.
const exhaustedTape = [];
const exhausted = await instantiate({{
  async spawn(epoch) {{
    exhaustedTape.push(["spawn", epoch]);
    if (epoch > 0) throw new Error("synthetic startup failure");
  }},
  async failure(epoch) {{ exhaustedTape.push(["failure", epoch]); }},
  close(epoch) {{ exhaustedTape.push(["close", epoch]); }},
}});
const exhaustedOutput = await exhausted.broker.run(exhausted.task, []);
if (exhaustedOutput.length !== 1 || exhaustedOutput[0] !== 1002n) {{
  throw new Error(`Fe exhaustion result drifted: ${{exhaustedOutput}}`);
}}
const expectedExhausted = JSON.stringify([
  ["spawn", 0], ["failure", 0], ["spawn", 1], ["spawn", 2], ["close", 2],
]);
if (JSON.stringify(exhaustedTape) !== expectedExhausted) {{
  throw new Error(`host selected or lost a lifecycle action: ${{JSON.stringify(exhaustedTape)}}`);
}}
if (exhausted.broker.activeCount() !== 0) throw new Error("exhausted scope leaked tokens");

// Failure of the observation mechanism is not misclassified as a child crash
// and does not consume the restart budget.
const transportTape = [];
const transport = await instantiate({{
  async spawn(epoch) {{ transportTape.push(["spawn", epoch]); }},
  async failure(epoch) {{
    transportTape.push(["failure", epoch]);
    throw new Error("synthetic observation transport failure");
  }},
  close(epoch) {{ transportTape.push(["close", epoch]); }},
}});
const transportOutput = await transport.broker.run(transport.task, []);
if (transportOutput.length !== 1 || transportOutput[0] !== 300001n) {{
  throw new Error(`Fe transport-failure result drifted: ${{transportOutput}}`);
}}
if (JSON.stringify(transportTape) !== JSON.stringify([
  ["spawn", 0], ["failure", 0], ["close", 0],
])) {{
  throw new Error(`transport failure was restarted by the host: ${{JSON.stringify(transportTape)}}`);
}}

// Parent cancellation reaches Fe exactly once. Fe selects Close during its
// cleanup continuation; the broker then preserves cancellation as terminal.
const cancelTape = [];
let observingFailure;
const cancellation = await instantiate({{
  async spawn(epoch) {{ cancelTape.push(["spawn", epoch]); }},
  failure(epoch, signal) {{
    cancelTape.push(["failure", epoch]);
    observingFailure = signal;
    return new Promise(() => {{}});
  }},
  close(epoch) {{ cancelTape.push(["close", epoch]); }},
}});
const controller = new AbortController();
const cancelledRun = cancellation.broker.run(
  cancellation.task,
  [],
  {{ signal: controller.signal }},
);
for (let attempt = 0; attempt < 100 && observingFailure === undefined; attempt += 1) {{
  await new Promise(resolve => setTimeout(resolve, 0));
}}
if (observingFailure === undefined) throw new Error("Fe never began runtime-failure observation");
controller.abort();
let cancellationError;
try {{ await cancelledRun; }} catch (error) {{ cancellationError = error; }}
if (cancellationError?.name !== "AbortError") {{
  throw new Error("parent cancellation did not remain terminal");
}}
if (!observingFailure.aborted) throw new Error("failure observation did not receive cancellation");
if (JSON.stringify(cancelTape) !== JSON.stringify([
  ["spawn", 0], ["failure", 0], ["close", 0],
])) {{
  throw new Error(`Fe cancellation cleanup drifted: ${{JSON.stringify(cancelTape)}}`);
}}
if (cancellation.broker.activeCount() !== 0) throw new Error("cancelled scope leaked tokens");
"#,
        adapter_url = format!("file://{}", adapter_path.display()),
        host_runtime_url = format!("file://{}", host_runtime_path.display()),
        wasm_path = wasm_path.display().to_string(),
    );
    std::fs::write(&test_path, script).unwrap();
    let output = std::process::Command::new("bun")
        .arg("run")
        .arg(&test_path)
        .output()
        .unwrap();
    assert!(
        output.status.success(),
        "compiled Fe Worker scope failed:\nstdout: {}\nstderr: {}",
        String::from_utf8_lossy(&output.stdout),
        String::from_utf8_lossy(&output.stderr),
    );
}
