//! Independent semantic gate for Fe-owned structured-child supervision.
//!
//! The fixed Worker runtime is intentionally absent. Wasmtime executes the Fe
//! restart-window reducer while this test supplies explicit expected states for
//! spawn, readiness, rolling-window reset, bounded restart, exhaustion, and
//! parent cancellation. Generated bytes are not a correctness oracle.

use std::path::Path;

use common::InputDb;
use driver::DriverDataBase;
use fe_codegen::{BackendKind, OptLevel, layout_for};
use hir::hir_def::HirIngot;
use url::Url;

type Params = (i32, i32, i32, i64, i32, i32, i64, i32, i32, i32, i64, i64);
type ResultLanes = (i32, i32, i64, i32, i32, i32, i64);

const SPAWN_REQUESTED: i32 = 0;
const READY: i32 = 1;
const FAILED: i32 = 2;
const BACKOFF_ELAPSED: i32 = 3;
const PARENT_CANCELLED: i32 = 4;

const NO_FAILURE: i32 = 0;
const STARTUP_FAILURE: i32 = 1;
const RUNTIME_FAILURE: i32 = 2;

const IDLE: i32 = 0;
const STARTING: i32 = 1;
const ACTIVE: i32 = 2;
const BACKOFF: i32 = 3;
const TERMINAL: i32 = 4;
const CANCELLED: i32 = 5;

const NO_ACTION: i32 = 0;
const SPAWN: i32 = 1;
const RESTART_AFTER: i32 = 2;
const CLOSE: i32 = 3;
const FAIL: i32 = 4;

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
struct State {
    epoch: i32,
    restarts: i32,
    window_started_ms: i64,
    phase: i32,
    last_failure: i32,
}

impl State {
    const INITIAL: Self = Self {
        epoch: 0,
        restarts: 0,
        window_started_ms: 0,
        phase: IDLE,
        last_failure: NO_FAILURE,
    };

    fn params(
        self,
        kind: i32,
        failure: i32,
        observed_epoch: i32,
        now_ms: i64,
        max_restarts: i32,
        window_ms: i64,
        backoff_ms: i64,
    ) -> Params {
        (
            kind,
            failure,
            observed_epoch,
            now_ms,
            self.epoch,
            self.restarts,
            self.window_started_ms,
            self.phase,
            self.last_failure,
            max_restarts,
            window_ms,
            backoff_ms,
        )
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
struct Step {
    state: State,
    action: i32,
    delay_ms: i64,
}

fn compile_policy() -> Vec<u8> {
    let path = Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("tests/fixtures/worker_supervision_policy_ingot");
    let url = Url::from_directory_path(path.canonicalize().unwrap()).unwrap();
    let mut db = DriverDataBase::default();
    assert!(!driver::init_ingot(&mut db, &url));
    let ingot = db.workspace().containing_ingot(&db, url).unwrap();
    let top_mod = ingot.root_mod(&db);
    let diagnostics = db.run_on_top_mod(top_mod).format_diags(&db);
    assert!(
        diagnostics.is_empty(),
        "worker supervision fixture diagnostics:\n{diagnostics}"
    );
    let wasm = BackendKind::Wasm
        .create()
        .compile(&db, top_mod, layout_for(BackendKind::Wasm), OptLevel::O0)
        .expect("Fe supervision policy should compile to Wasm")
        .into_bytecode()
        .expect("Wasm bytes");
    wasmparser::validate(&wasm).expect("supervision policy Wasm should validate");
    wasm
}

fn decode(lanes: ResultLanes) -> Step {
    Step {
        state: State {
            epoch: lanes.0,
            restarts: lanes.1,
            window_started_ms: lanes.2,
            phase: lanes.3,
            last_failure: lanes.4,
        },
        action: lanes.5,
        delay_ms: lanes.6,
    }
}

#[test]
fn fe_policy_owns_bounded_restart_backoff_exhaustion_and_parent_cancellation() {
    let wasm = compile_policy();
    let engine = wasmtime::Engine::default();
    let module = wasmtime::Module::new(&engine, wasm).unwrap();
    let mut store = wasmtime::Store::new(&engine, ());
    let instance = wasmtime::Instance::new(&mut store, &module, &[]).unwrap();
    let decide = instance
        .get_typed_func::<Params, ResultLanes>(&mut store, "supervise")
        .unwrap();

    let call =
        |store: &mut wasmtime::Store<()>, state: State, kind, failure, observed_epoch, now| {
            decode(
                decide
                    .call(
                        store,
                        state.params(kind, failure, observed_epoch, now, 2, 50, 10),
                    )
                    .unwrap(),
            )
        };

    let spawned = call(
        &mut store,
        State::INITIAL,
        SPAWN_REQUESTED,
        NO_FAILURE,
        0,
        0,
    );
    assert_eq!(spawned.action, SPAWN);
    assert_eq!(spawned.state.phase, STARTING);

    let duplicate_spawn = call(&mut store, spawned.state, SPAWN_REQUESTED, NO_FAILURE, 0, 0);
    assert_eq!(duplicate_spawn.state, spawned.state);
    assert_eq!(duplicate_spawn.action, NO_ACTION);

    let ready = call(&mut store, spawned.state, READY, NO_FAILURE, 0, 1);
    assert_eq!(ready.action, NO_ACTION);
    assert_eq!(ready.state.phase, ACTIVE);

    let failed = call(&mut store, ready.state, FAILED, RUNTIME_FAILURE, 0, 10);
    assert_eq!(
        failed,
        Step {
            state: State {
                epoch: 1,
                restarts: 1,
                window_started_ms: 10,
                phase: BACKOFF,
                last_failure: RUNTIME_FAILURE,
            },
            action: RESTART_AFTER,
            delay_ms: 10,
        }
    );

    let stale_backoff = call(&mut store, failed.state, BACKOFF_ELAPSED, NO_FAILURE, 0, 15);
    assert_eq!(stale_backoff.state, failed.state);
    assert_eq!(stale_backoff.action, NO_ACTION);

    let respawn = call(&mut store, failed.state, BACKOFF_ELAPSED, NO_FAILURE, 1, 20);
    assert_eq!(respawn.action, SPAWN);
    assert_eq!(respawn.state.phase, STARTING);

    let stale_ready = call(&mut store, respawn.state, READY, NO_FAILURE, 0, 21);
    assert_eq!(stale_ready.state, respawn.state);
    assert_eq!(stale_ready.action, NO_ACTION);

    // At 70 ms the previous 50 ms window has expired. The new startup failure
    // begins a fresh budget instead of inheriting the old attempt.
    let reset = call(&mut store, respawn.state, FAILED, STARTUP_FAILURE, 1, 70);
    assert_eq!(reset.state.epoch, 2);
    assert_eq!(reset.state.restarts, 1);
    assert_eq!(reset.state.window_started_ms, 70);
    assert_eq!(reset.action, RESTART_AFTER);

    let second_spawn = call(&mut store, reset.state, BACKOFF_ELAPSED, NO_FAILURE, 2, 80);
    let second_failure = call(
        &mut store,
        second_spawn.state,
        FAILED,
        STARTUP_FAILURE,
        2,
        90,
    );
    assert_eq!(second_failure.state.restarts, 2);
    assert_eq!(second_failure.state.epoch, 3);
    assert_eq!(second_failure.action, RESTART_AFTER);

    let third_spawn = call(
        &mut store,
        second_failure.state,
        BACKOFF_ELAPSED,
        NO_FAILURE,
        3,
        100,
    );
    let exhausted = call(
        &mut store,
        third_spawn.state,
        FAILED,
        RUNTIME_FAILURE,
        3,
        110,
    );
    assert_eq!(exhausted.state.phase, TERMINAL);
    assert_eq!(exhausted.state.epoch, 3);
    assert_eq!(exhausted.action, FAIL);
    assert_eq!(exhausted.delay_ms, 0);

    let inert = call(
        &mut store,
        exhausted.state,
        BACKOFF_ELAPSED,
        NO_FAILURE,
        3,
        120,
    );
    assert_eq!(inert.state, exhausted.state);
    assert_eq!(inert.action, NO_ACTION);

    let cancelled = call(&mut store, ready.state, PARENT_CANCELLED, NO_FAILURE, 0, 15);
    assert_eq!(cancelled.state.phase, CANCELLED);
    assert_eq!(cancelled.action, CLOSE);
    let after_cancel = call(&mut store, cancelled.state, FAILED, RUNTIME_FAILURE, 0, 16);
    assert_eq!(after_cancel.state, cancelled.state);
    assert_eq!(after_cancel.action, NO_ACTION);
}
