[ingot]
name = "mandelbrot_proof_commitment"
version = "0.1.0"

[dependencies]
core = "../../../../ingots/core"
mandelbrot_proof_kernel = "../kernel"
poseidon_bn254 = "../../../../ingots/poseidon_bn254"
poseidon_merkle = "../../../../ingots/poseidon_merkle"
