[ingot]
name = "mandelbrot_proof_recursive_air_baby_bear"
version = "0.1.0"

[dependencies]
canonical_words = "../../../../ingots/canonical_words"
core = "../../../../ingots/core"
mandelbrot_proof_recursive = "../recursive"
mandelbrot_proof_recursive_baby_bear = "../recursive-baby-bear"
poseidon_baby_bear = "../../../../ingots/poseidon_baby_bear"
precision = "../../../sketches/precision"
quadratic_plan = "../../../../ingots/quadratic_plan"
