#!/usr/bin/env python3
"""Generate/check the typed sparse-Cl(4,1) runtime-center cyclide render."""

import argparse
import sys
from pathlib import Path

sys.dont_write_bytecode = True

from gen_cga_sandwich_support_cl41 import (  # noqa: E402
    LEAVES,
    METRIC,
    POINT_SUPPORT,
    Poly,
    SPHERE_SUPPORT,
    VECTOR_SUPPORT,
    derive,
    emit_helper_expression,
    path,
    tree,
)

HERE = Path(__file__).resolve().parent
OUTPUT = HERE / "cga_inversion_cyclide_recursive_support.fe"


def assert_homogeneous_semantics(sandwich):
    """Prove the recurrence-derived raw vector's homogeneous interpretation."""
    x, y, z = (Poly.var(name) for name in ("x", "y", "z"))
    cx, cy = (Poly.var(name) for name in ("cx", "cy"))
    radius2 = x * x + y * y + z * z
    center2 = cx * cx + cy * cy
    substitutions = {
        "p1": x,
        "p2": y,
        "p4": z,
        "p8": radius2.scale(1 / 2) - Poly.constant(1 / 2),
        "p16": radius2.scale(1 / 2) + Poly.constant(1 / 2),
        "s1": cx,
        "s2": cy,
        "s8": center2.scale(1 / 2) - Poly.constant(1),
        "s16": center2.scale(1 / 2),
    }

    def substitute(polynomial):
        result = Poly()
        for monomial, coefficient in polynomial.terms.items():
            term = Poly.constant(coefficient)
            for variable in monomial:
                term = term * substitutions[variable]
            result = result + term
        return result

    raw = {index: substitute(sandwich[index]) for index in VECTOR_SUPPORT}
    weight = raw[16] - raw[8]
    vx, vy = x - cx, y - cy
    rho2 = vx * vx + vy * vy + z * z
    assert weight == -rho2
    assert raw[1] == weight * cx - vx
    assert raw[2] == weight * cy - vy
    assert raw[4] == -z


def assert_structure(generated, output_tree):
    loop_start = generated.index("    while i < 72 {")
    loop_end = generated.index("        i = i + 1", loop_start)
    hot_path = generated[loop_start:loop_end]
    assert "let point: MvTF<5>" in hot_path
    assert "let sphere: MvTF<5>" in hot_path
    assert "let sandwich: MvTF<5> = sandwich_support_cl41(sphere, point)" in hot_path
    assert "let raw_1: f32 = sandwich." in hot_path
    assert "let raw_16: f32 = sandwich." in hot_path
    assert "let weight: f32 = raw_16 - raw_8" in hot_path
    assert "let safe_weight: f32 = if weight > -0.0004 { -0.0004 } else { weight }" in hot_path
    assert "let weight_adjust: f32 = safe_weight - weight" in hot_path
    assert "let qx: f32 = (raw_1 + weight_adjust * inv_cx) / safe_weight" in hot_path
    assert "let qy: f32 = (raw_2 + weight_adjust * inv_cy) / safe_weight" in hot_path
    assert generated.count("fn sandwich_support_cl41(sphere: MvTF<5>, point: MvTF<5>) -> MvTF<5>") == 1
    assert output_tree in generated
    forbidden = (
        "q=c+(p-c)",
        "inv_cx + vx /",
        "inv_cy + vy /",
        "z / safe_rho2",
        "rho2 < 0.0004",
    )
    for text in forbidden:
        assert text not in generated
    assert generated.count("__bitcast(upper_color)") == 1
    assert generated.count("__bitcast(lower_color)") == 1
    assert generated.count("__bitcast(sky_color)") == 1
    assert generated.count("let shade: i32 = 38 + 24 * (i >> 3)") == 1
    assert "38 + i * 3" not in generated


def generate():
    _, sandwich = derive()
    assert_homogeneous_semantics(sandwich)
    output_tree = tree(
        [emit_helper_expression(sandwich[i]) if i in VECTOR_SUPPORT else "zero" for i in range(LEAVES)]
    )
    point_values = {
        1: "x",
        2: "y",
        4: "z",
        8: "point_e4",
        16: "point_e5",
    }
    sphere_values = {1: "inv_cx", 2: "inv_cy", 8: "sphere_e4", 16: "sphere_e5"}
    point_tree = tree([point_values.get(i, "zero") for i in range(LEAVES)])
    sphere_tree = tree([sphere_values.get(i, "zero") for i in range(LEAVES)])
    raw_reads = "\n".join(
        f"        let raw_{index}: f32 = sandwich.{path(index)}.s" for index in VECTOR_SUPPORT
    )
    generated = f'''// @generated by gen_cga_inversion_cyclide_recursive_support.py; do not edit.
// Runtime-center cyclide DE whose inversion is the typed support-specialized
// recursive/Cayley Cl(4,1) sandwich. The scalar D1 study remains a baseline.

extern {{
    fn __f32_from_i32(_: i32) -> f32
    fn __sqrt_f32(_: f32) -> f32
    const fn __bitcast<From, To>(_: From) -> To
}}

pub struct ScF {{ pub s: f32 }}
pub struct NdF<A> {{ pub a: A, pub b: A }}
impl Copy for ScF {{}}
impl<A: Copy> Copy for NdF<A> {{}}

recursive type fn MvTF<const N: usize>() -> (*) {{
    match N {{
        0 => ScF
        _ => NdF<MvTF<{{N - 1}}>>
    }}
}}

#[inline(always)]
fn sandwich_support_cl41(sphere: MvTF<5>, point: MvTF<5>) -> MvTF<5> {{
    let zero: f32 = point.a.a.a.a.a.s
    {output_tree}
}}

pub fn cga_inversion_cyclide_recursive_support(
    px: i32,
    py: i32,
    cam_x: f32,
    cam_y: f32,
    zoom: f32,
    inv_cx: f32,
    inv_cy: f32,
) -> u32 {{
    let fx: f32 = __f32_from_i32(px)
    let fy: f32 = __f32_from_i32(py)
    let sx: f32 = (fx - 64.0) * zoom
    let sy: f32 = (fy - 64.0) * zoom
    let rz: f32 = 1.8
    let inv_len: f32 = 1.0 / __sqrt_f32(sx * sx + sy * sy + rz * rz)
    let rdx: f32 = sx * inv_len
    let rdy: f32 = sy * inv_len
    let rdz: f32 = rz * inv_len

    let mut t: f32 = 0.0
    let mut i: i32 = 0
    while i < 72 {{
        let x: f32 = cam_x + rdx * t
        let y: f32 = cam_y + rdy * t
        let z: f32 = -4.0 + rdz * t
        let zero: f32 = x - x
        let radius2: f32 = x * x + y * y + z * z
        let center2: f32 = inv_cx * inv_cx + inv_cy * inv_cy
        let point_e4: f32 = (radius2 - 1.0) * 0.5
        let point_e5: f32 = (radius2 + 1.0) * 0.5
        let sphere_e4: f32 = center2 * 0.5 - 1.0
        let sphere_e5: f32 = center2 * 0.5
        let point: MvTF<5> = {point_tree}
        let sphere: MvTF<5> = {sphere_tree}
        let sandwich: MvTF<5> = sandwich_support_cl41(sphere, point)
{raw_reads}
        let weight: f32 = raw_16 - raw_8
        // The recurrence-derived raw vector obeys raw_xy = weight*c - (p-c),
        // with non-positive weight. Adjusting its center term along with the
        // clamped weight preserves the regularized homogeneous point exactly.
        let safe_weight: f32 = if weight > -0.0004 {{ -0.0004 }} else {{ weight }}
        let weight_adjust: f32 = safe_weight - weight
        let qx: f32 = (raw_1 + weight_adjust * inv_cx) / safe_weight
        let qy: f32 = (raw_2 + weight_adjust * inv_cy) / safe_weight
        let qz: f32 = raw_4 / safe_weight

        let tx: f32 = qx + 0.62
        let ty: f32 = qy - 0.08
        let ring_radius: f32 = __sqrt_f32(tx * tx + ty * ty) - 0.58
        let base: f32 = __sqrt_f32(ring_radius * ring_radius + qz * qz) - 0.17
        // |weight| is the conformal distance scale for the unit inversion.
        let distance: f32 = base * -safe_weight
        t = t + distance * 0.18
        if distance < 0.0022 {{
            let shade: i32 = 38 + 24 * (i >> 3)
            let upper: bool = qy > 0.0
            if upper {{
                let upper_color: i32 = shade + 88 * 256 + (255 - shade) * 65536 + -16777216
                return __bitcast(upper_color)
            }}
            let lower_color: i32 = 56 + shade * 256 + 224 * 65536 + -16777216
            return __bitcast(lower_color)
        }}
        i = i + 1
    }}
    let sky_color: i32 = 7 + 11 * 256 + 25 * 65536 + -16777216
    __bitcast(sky_color)
}}
'''
    assert_structure(generated, output_tree)
    return generated


def stats():
    first, sandwich = derive()
    return (
        f"depth=5 metric={METRIC} sphere_support={SPHERE_SUPPORT} "
        f"point_support={POINT_SUPPORT} first_support={sum(bool(v.terms) for v in first)} "
        f"sandwich_support={tuple(i for i,v in enumerate(sandwich) if v.terms)} "
        "typed_sandwich_calls_per_de_step=1 de_steps=72 runtime_f32_inputs=5"
    )


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--stdout", action="store_true")
    parser.add_argument("--stats", action="store_true")
    args = parser.parse_args()
    expected = generate()
    if args.stdout:
        print(expected, end="")
    elif args.check:
        if not OUTPUT.exists() or OUTPUT.read_text() != expected:
            raise SystemExit(f"stale generated fixture: run {Path(__file__).name}")
        print(f"{OUTPUT.name} is current")
    else:
        OUTPUT.write_text(expected)
        print(f"wrote {OUTPUT}")
    if args.stats:
        print(stats())


if __name__ == "__main__":
    main()
