#!/usr/bin/env python3
"""Generate/check the runtime Cl(4,1) MvT<5> conformal sandwich probe."""

import argparse
import sys
from pathlib import Path

sys.dont_write_bytecode = True

from gen_clifford_gp_f32_mvt5 import (  # noqa: E402
    DEPTH,
    LEAVES,
    concrete_type,
    helper_family,
    path,
    tree,
)

HERE = Path(__file__).resolve().parent
OUTPUT = HERE / "cga_sandwich_recursive_f32_mvt5.fe"
EXPECTED_GP_EXPANSION = 29_118


def selector(lo, hi):
    if hi - lo == 1:
        return f"sandwich.{path(lo)}.s"
    mid = (lo + hi) // 2
    return f"if k < {mid} {{ {selector(lo, mid)} }} else {{ {selector(mid, hi)} }}"


def sparse_tree(values):
    return tree([values.get(index, "zero") for index in range(LEAVES)])


def assert_structure(helpers, generated, point_values, sphere_values, point, sphere):
    assert DEPTH == 5
    assert LEAVES == 32
    assert point_values == {
        1: "x",
        2: "y",
        4: "z",
        8: "point_e4",
        16: "point_e5",
    }
    assert sphere_values == {1: "s1", 8: "s8", 16: "s16"}
    assert point == sparse_tree(point_values)
    assert sphere == sparse_tree(sphere_values)
    assert generated.count(f"let point: MvTF<5> = {point}") == 1
    assert generated.count(f"let sphere: MvTF<5> = {sphere}") == 1
    assert helpers.count("#[inline(always)]") == 4 * (DEPTH + 1)
    for depth in range(DEPTH + 1):
        for family in ("add", "neg", "invol", "gp"):
            assert helpers.count(f"fn {family}_{depth}(") == 1
    for depth in range(1, DEPTH + 1):
        body = helpers.split(f"fn gp_{depth}(", 1)[1].split("\n}", 1)[0]
        child = depth - 1
        assert body.count(f"gp_{child}(") == 4
        assert body.count(f"gp_{child}(x.a, y.a)") == 1
        assert body.count(f"gp_{child}(x.b, invol_{child}(y.b))") == 1
        assert body.count(f"gp_{child}(x.a, y.b)") == 1
        assert body.count(f"gp_{child}(x.b, invol_{child}(y.a))") == 1
        assert body.count(f"add_{child}(ab, bha)") == 1
        if depth < DEPTH:
            assert body.count(f"add_{child}(aa, bhb)") == 1
            assert f"neg_{child}(bhb)" not in body
        else:
            assert body.count(f"add_{child}(aa, neg_{child}(bhb))") == 1
    assert generated.count("let first_product:") == 1
    assert generated.count("let sandwich:") == 1
    assert generated.count("= gp_5(sphere, point)") == 1
    assert generated.count("= gp_5(first_product, sphere)") == 1
    assert generated.count("let k: i32 = px + py * 8") == 1
    assert generated.count("__i32_from_f32(coefficient * 256.0)") == 1
    for index in range(LEAVES):
        assert generated.count(f"sandwich.{path(index)}.s") == 1


def generate():
    helpers = helper_family()
    mvt5 = concrete_type(DEPTH)
    point_values = {
        1: "x",
        2: "y",
        4: "z",
        8: "point_e4",
        16: "point_e5",
    }
    sphere_values = {1: "s1", 8: "s8", 16: "s16"}
    point = sparse_tree(point_values)
    sphere = sparse_tree(sphere_values)
    selected = selector(0, LEAVES)
    generated = f'''// @generated by gen_cga_sandwich_f32_mvt5.py; do not edit.
// Runtime Cl(4,1) conformal sandwich over the shared generated GP helpers.
// e0=(e5-e4)/2, einf=e4+e5; DFS leaf i is blade bitset i.
// The result is the raw projective S*P*S value, scaled by 256 for observation.

extern {{
    fn __i32_from_f32(_: f32) -> i32
    const fn __bitcast<From, To>(_: From) -> To
}}

pub struct ScF {{ pub s: f32 }}
pub struct NdF<A> {{ pub a: A, pub b: A }}
impl Copy for ScF {{}}
impl<A: Copy> Copy for NdF<A> {{}}

recursive type fn MvTF<const N: usize>() -> (*) {{
    match N {{
        0 => ScF
        _ => NdF<MvTF<{{N - 1}}>>
    }}
}}

pub fn cga_sandwich_cl41_mvt5_render(
    px: i32,
    py: i32,
    x: f32,
    y: f32,
    z: f32,
    s1: f32,
    s8: f32,
    s16: f32,
) -> u32 {{
    // A runtime zero keeps sparse aggregate subtrees value-carried instead of
    // materializing backend-unsupported aggregate constant regions.
    let zero: f32 = x - x
    let radius2: f32 = x * x + y * y + z * z
    let point_e4: f32 = (radius2 - 1.0) * 0.5
    let point_e5: f32 = (radius2 + 1.0) * 0.5
    let point: MvTF<5> = {point}
    let sphere: MvTF<5> = {sphere}
    let first_product: {mvt5} = gp_5(sphere, point)
    let sandwich: {mvt5} = gp_5(first_product, sphere)
    let k: i32 = px + py * 8
    let coefficient: f32 = {selected}
    __bitcast(__i32_from_f32(coefficient * 256.0))
}}

{helpers}
'''
    assert_structure(helpers, generated, point_values, sphere_values, point, sphere)
    return generated


def stats():
    return (
        f"depth={DEPTH} leaves={LEAVES} helpers={4 * (DEPTH + 1)} "
        f"gp5_calls=2 base_multiplications={2 * (4**DEPTH)} "
        f"combine_scalar_additions={2 * 992} selector_leaves={LEAVES} "
        f"runtime_f32_inputs=6 expected_gp_expansion={2 * EXPECTED_GP_EXPANSION}"
    )


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--stdout", action="store_true")
    parser.add_argument("--stats", action="store_true")
    args = parser.parse_args()
    expected = generate()
    if args.stdout:
        print(expected, end="")
    elif args.check:
        if not OUTPUT.exists() or OUTPUT.read_text() != expected:
            raise SystemExit(f"stale generated fixture: run {Path(__file__).name}")
        print(f"{OUTPUT.name} is current")
    else:
        OUTPUT.write_text(expected)
        print(f"wrote {OUTPUT}")
    if args.stats:
        print(stats())


if __name__ == "__main__":
    main()
