#!/usr/bin/env python3
"""Generate/check the call-free depth-5 recursive f32 value probe."""

import argparse
import sys
from pathlib import Path

sys.dont_write_bytecode = True

HERE = Path(__file__).resolve().parent
OUTPUT = HERE / "mvt5_f32_render.fe"


def path(index):
    return ".".join("b" if index & (1 << bit) else "a" for bit in range(4, -1, -1))


def tree(expressions):
    if len(expressions) == 1:
        return f"ScF {{ s: {expressions[0]} }}"
    half = len(expressions) // 2
    return f"NdF {{ a: {tree(expressions[:half])}, b: {tree(expressions[half:])} }}"


def selector(lo, hi):
    if hi - lo == 1:
        return f"rebuilt.{path(lo)}.s"
    mid = (lo + hi) // 2
    return f"if k < {mid} {{ {selector(lo, mid)} }} else {{ {selector(mid, hi)} }}"


def generate():
    params = ",\n    ".join(f"c{i}: f32" for i in range(32))
    initial = tree([f"c{i}" for i in range(32)])
    transformed = [
        f"copied.{path(i)}.s * {2 * i + 1}.0 + {1000 + i}.0"
        for i in range(32)
    ]
    rebuilt = tree(transformed)
    selected = selector(0, 32)
    return f'''// @generated by gen_mvt5_f32_render.py; do not edit.
// Depth-5 recursive-value/f32 prerequisite, not the runtime CGA product.

extern {{
    fn __i32_from_f32(_: f32) -> i32
    const fn __bitcast<From, To>(_: From) -> To
}}

pub struct ScF {{ pub s: f32 }}
pub struct NdF<A> {{ pub a: A, pub b: A }}
impl Copy for ScF {{}}
impl<A: Copy> Copy for NdF<A> {{}}

recursive type fn MvTF<const N: usize>() -> (*) {{
    match N {{
        0 => ScF
        _ => NdF<MvTF<{{N - 1}}>>
    }}
}}

pub fn mvt5_f32_render(
    px: i32,
    py: i32,
    {params},
) -> u32 {{
    let tree: MvTF<5> = {initial}
    let copied: MvTF<5> = tree
    let rebuilt: MvTF<5> = {rebuilt}
    let k: i32 = px + py * 8
    let selected: f32 = {selected}
    __bitcast(__i32_from_f32(selected))
}}
'''


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--stdout", action="store_true")
    args = parser.parse_args()
    expected = generate()
    if args.stdout:
        print(expected, end="")
    elif args.check:
        if not OUTPUT.exists() or OUTPUT.read_text() != expected:
            raise SystemExit(f"stale generated fixture: run {Path(__file__).name}")
        print("mvt5_f32_render.fe is current")
    else:
        OUTPUT.write_text(expected)
        print(f"wrote {OUTPUT}")


if __name__ == "__main__":
    main()
