#!/usr/bin/env python3
"""Generate/check the fixed-signature Cl(4,1) MvT<5> runtime GP probe."""

import argparse
import sys
from pathlib import Path

sys.dont_write_bytecode = True

HERE = Path(__file__).resolve().parent
OUTPUT = HERE / "clifford_gp_recursive_f32_mvt5.fe"
DEPTH = 5
LEAVES = 1 << DEPTH


def concrete_type(depth):
    ty = "ScF"
    for _ in range(depth):
        ty = f"NdF<{ty}>"
    return ty


def path(index, depth=DEPTH):
    return ".".join(
        "b" if index & (1 << bit) else "a"
        for bit in range(depth - 1, -1, -1)
    )


def tree(expressions):
    if len(expressions) == 1:
        return f"ScF {{ s: {expressions[0]} }}"
    half = len(expressions) // 2
    return f"NdF {{ a: {tree(expressions[:half])}, b: {tree(expressions[half:])} }}"


def selector(lo, hi):
    if hi - lo == 1:
        return f"product.{path(lo)}.s"
    mid = (lo + hi) // 2
    return f"if k < {mid} {{ {selector(lo, mid)} }} else {{ {selector(mid, hi)} }}"


def helper_family():
    helpers = []
    helpers.append(
        """#[inline(always)]
fn add_0(x: ScF, y: ScF) -> ScF {
    ScF { s: x.s + y.s }
}
#[inline(always)]
fn neg_0(x: ScF) -> ScF {
    ScF { s: -x.s }
}
#[inline(always)]
fn invol_0(x: ScF) -> ScF {
    x
}
#[inline(always)]
fn gp_0(x: ScF, y: ScF) -> ScF {
    ScF { s: x.s * y.s }
}"""
    )
    for depth in range(1, DEPTH + 1):
        ty = concrete_type(depth)
        child = depth - 1
        signed_cross = f"neg_{child}(bhb)" if depth == DEPTH else "bhb"
        helpers.append(
            f"""#[inline(always)]
fn add_{depth}(x: {ty}, y: {ty}) -> {ty} {{
    NdF {{ a: add_{child}(x.a, y.a), b: add_{child}(x.b, y.b) }}
}}
#[inline(always)]
fn neg_{depth}(x: {ty}) -> {ty} {{
    NdF {{ a: neg_{child}(x.a), b: neg_{child}(x.b) }}
}}
#[inline(always)]
fn invol_{depth}(x: {ty}) -> {ty} {{
    NdF {{ a: invol_{child}(x.a), b: neg_{child}(invol_{child}(x.b)) }}
}}
#[inline(always)]
fn gp_{depth}(x: {ty}, y: {ty}) -> {ty} {{
    let aa = gp_{child}(x.a, y.a)
    let bhb = gp_{child}(x.b, invol_{child}(y.b))
    let ab = gp_{child}(x.a, y.b)
    let bha = gp_{child}(x.b, invol_{child}(y.a))
    NdF {{ a: add_{child}(aa, {signed_cross}), b: add_{child}(ab, bha) }}
}}"""
        )
    return "\n\n".join(helpers)


def generate():
    params = ",\n    ".join(
        [f"x{i}: f32" for i in range(LEAVES)]
        + [f"y{i}: f32" for i in range(LEAVES)]
    )
    x_tree = tree([f"x{i}" for i in range(LEAVES)])
    y_tree = tree([f"y{i}" for i in range(LEAVES)])
    selected = selector(0, LEAVES)
    helpers = helper_family()
    assert helpers.count("#[inline(always)]") == 4 * (DEPTH + 1)
    for depth in range(DEPTH + 1):
        for family in ("add", "neg", "invol", "gp"):
            assert helpers.count(f"fn {family}_{depth}(") == 1
    assert "add_4(aa, neg_4(bhb))" in helpers
    assert helpers.count("neg_4(bhb)") == 1
    mvt5 = concrete_type(DEPTH)
    return f'''// @generated by gen_clifford_gp_f32_mvt5.py; do not edit.
// Fixed Cl(4,1) specialization of the recursive MvT<5> geometric product.
// DFS leaf i is blade bitset i. Metric signs by level are +,+,+,+,-.
// This is one runtime product, not the conformal S*P*S sandwich.

extern {{
    fn __i32_from_f32(_: f32) -> i32
    const fn __bitcast<From, To>(_: From) -> To
}}

pub struct ScF {{ pub s: f32 }}
pub struct NdF<A> {{ pub a: A, pub b: A }}
impl Copy for ScF {{}}
impl<A: Copy> Copy for NdF<A> {{}}

recursive type fn MvTF<const N: usize>() -> (*) {{
    match N {{
        0 => ScF
        _ => NdF<MvTF<{{N - 1}}>>
    }}
}}

pub fn clifford_gp_cl41_mvt5_render(
    px: i32,
    py: i32,
    {params},
) -> u32 {{
    let x: MvTF<5> = {x_tree}
    let y: MvTF<5> = {y_tree}
    let product: {mvt5} = gp_5(x, y)
    let k: i32 = px + py * 8
    let coefficient: f32 = {selected}
    __bitcast(__i32_from_f32(coefficient))
}}

{helpers}
'''


def stats():
    multiplications = 4**DEPTH
    additions = sum((4 ** (DEPTH - depth)) * (2**depth) for depth in range(1, DEPTH + 1))
    return (
        f"depth={DEPTH} leaves={LEAVES} helpers={4 * (DEPTH + 1)} "
        f"base_multiplications={multiplications} combine_scalar_additions={additions} "
        f"selector_leaves={LEAVES} broadcast_f32s={2 * LEAVES}"
    )


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--stdout", action="store_true")
    parser.add_argument("--stats", action="store_true")
    args = parser.parse_args()
    expected = generate()
    if args.stdout:
        print(expected, end="")
    elif args.check:
        if not OUTPUT.exists() or OUTPUT.read_text() != expected:
            raise SystemExit(f"stale generated fixture: run {Path(__file__).name}")
        print(f"{OUTPUT.name} is current")
    else:
        OUTPUT.write_text(expected)
        print(f"wrote {OUTPUT}")
    if args.stats:
        print(stats())


if __name__ == "__main__":
    main()
