[ingot]
name = "classic_quilting_oracle"
version = "0.1.0"

[dependencies]
core = { path = "../core" }
quilting_domain = { path = "../quilting_domain" }
quilting_quaternion = { path = "../quilting_quaternion" }
quilting_qb = { path = "../quilting_qb" }
