import { initWebGPURender, renderFrame, submitOffscreenFrame, verifyView } from "../webgpu-keystone/webgpu-runner.js";
import { createQcgaActor } from "./worker-client.js";
const $=id=>document.getElementById(id), query=new URLSearchParams(location.search);
const offscreen=query.get("acceptance")==="offscreen", verifyOff=query.get("verify")==="off";
const DEFAULT_FRAME={origin_x:0,origin_y:0,origin_z:-4,projection_norm_squared:3.24,pixel_scale:0.018,a:0.85,b:1.25,c:0.65,d:0.55,e:-0.40,f:0.30,g:-0.16,h:0.1375,i:-0.04,j:-0.979125};
const counters={fetches:[],workerCreates:0,readbacks:0};
window.__qcgaAcceptance={state:"pending",presentation:offscreen?"offscreen":"canvas",counters};
const load=async(path,kind)=>{counters.fetches.push(path);const r=await fetch(path);if(!r.ok)throw new Error(`${path}: HTTP ${r.status}`);return kind==="json"?r.json():kind==="text"?r.text():r.arrayBuffer();};
const fnv=bytes=>{let h=0x811c9dc5;for(const b of bytes){h=Math.imul(h^b,0x01000193)>>>0;}return h;};
const status=(state,detail,extra={})=>{$("state").textContent=state.toUpperCase();$("detail").textContent=detail;$("banner").className=`banner ${state}`;window.__qcgaAcceptance={state,detail,presentation:offscreen?"offscreen":"canvas",counters:{fetches:[...counters.fetches],workerCreates:counters.workerCreates,readbacks:counters.readbacks},...extra};$("acceptance").textContent=JSON.stringify(window.__qcgaAcceptance);};
try{
  const [layout,wgsl,source]=await Promise.all([load("gen/layout.json","json"),load("gen/frag.wgsl","text"),load("gen/kernel.fe","text")]);
  const [reference,wasm]=verifyOff?[null,null]:await Promise.all([load("gen/reference.json","json"),load("gen/actor-canonical.wasm","bytes")]);
  $("source").textContent=source;$("wgsl").textContent=wgsl;$("meta").textContent=`Fe ${layout.provenance.fe_rev.slice(0,12)} · Sonatina ${layout.provenance.sonatina_rev.slice(0,12)}${reference?` · reference 0x${reference.fnv1a32.toString(16)}`:" · unverified presentation"}`;
  const gpu=await initWebGPURender(wgsl,layout,offscreen?null:$("view"));if(!gpu.ok)throw new Error(gpu.reason);
  const values=layout.params.map(({name})=>DEFAULT_FRAME[name]);
  const gpuRender=async(frameValues=values)=>{offscreen?submitOffscreenFrame(gpu,frameValues):renderFrame(gpu,frameValues);return{submitted:true};};
  const gpuVerify=async(frameValues=values)=>{counters.readbacks++;const r=await verifyView(gpu,frameValues);if(!r.ok)throw new Error(r.reason);return r.rgba;};
  if(verifyOff){await gpuRender();status("presentation","GPU submitted with zero Wasm/readback",{verified:false,presentation:offscreen?"offscreen":"canvas",adapter:gpu.adapter});}
  else {counters.workerCreates++;const actor=await createQcgaActor({wasm,width:128,height:128,params:layout.params,gpuRender,gpuVerify});addEventListener("pagehide",()=>actor.close(),{once:true});await actor.render({...DEFAULT_FRAME,generation:1});const oracleStarted=performance.now();const [cpu,gpuBytes]=await Promise.all([actor.wasm({...DEFAULT_FRAME,generation:2}),actor.gpu({...DEFAULT_FRAME,generation:2})]);const oracleMs=performance.now()-oracleStarted;const equal=cpu.length===gpuBytes.length&&cpu.every((v,i)=>v===gpuBytes[i]);const hash=fnv(cpu);if(!equal||hash!==reference.fnv1a32)throw new Error(`hash/equality failure wasm=${hash} expected=${reference.fnv1a32}`);status("green",`one-call Fe/Wasm frame = GPU · 0x${hash.toString(16)} · oracle ${oracleMs.toFixed(1)} ms`,{verified:true,pixels:16384,canonicalCalls:1,wasmHash:hash,gpuHash:fnv(gpuBytes),oracleMs,adapter:gpu.adapter});$("verify").onclick=()=>location.reload();}
  let controlFrame=0;for(const input of document.querySelectorAll("#shape-controls input")){const output=input.parentElement.querySelector("output");input.oninput=()=>{DEFAULT_FRAME[input.dataset.param]=Number(input.value);output.value=Number(input.value).toFixed(input.dataset.param==="pixel_scale"?4:3);if(controlFrame)return;controlFrame=requestAnimationFrame(async()=>{controlFrame=0;await gpuRender(layout.params.map(({name})=>DEFAULT_FRAME[name]));status("presentation","interactive typed QCGA frame · verification invalidated",{verified:false,interactive:true,adapter:gpu.adapter});});};}
  $("verify").onclick=()=>{const next=new URL(location.href);next.searchParams.delete("verify");location.href=next;};
  let pixelated=false;$("pixels").onclick=()=>{$("view").style.imageRendering=(pixelated=!pixelated)?"pixelated":"auto";};
  const stage=$("view").parentElement,loupe=$("loupe"),snapshot=offscreen?null:$("view").toDataURL();if(snapshot)loupe.style.backgroundImage=`url(${snapshot})`;stage.onpointermove=e=>{const r=stage.getBoundingClientRect(),x=Math.max(0,Math.min(127,Math.floor((e.clientX-r.left)*128/r.width))),y=Math.max(0,Math.min(127,Math.floor((e.clientY-r.top)*128/r.height)));$("inspect").textContent=`pixel (${x}, ${y})`;if(!snapshot)return;loupe.style.display="block";loupe.style.left=`${e.clientX-r.left-75}px`;loupe.style.top=`${e.clientY-r.top-75}px`;loupe.style.backgroundSize=`${r.width*4}px ${r.height*4}px`;loupe.style.backgroundPosition=`${-x*r.width/32+75}px ${-y*r.height/32+75}px`;};stage.onpointerleave=()=>loupe.style.display="none";
}catch(error){status("red",String(error));throw error;}
