#!/usr/bin/env python3
"""Regenerate the Fixed<L> bit-identical oracle gate fixture.

Emits thin per-static-limb wasm-export wrappers around the general
`precision::fixed::{mul, add, sub, sqr, escape_sample}` at each L in LS. Faithful
reproduction of the hand-checked L=4/L=8 style, extended to L in {2,4,6,8}.
"""

LS = [2, 4, 6, 8]

HEADER = '''//! Gate fixture for the `Fixed<L>` bit-identical oracle
//! (SHARED_LIMB_CORE_DESIGN.md section 3; precision axis). NOT the source of
//! truth: these are thin, per-limb wasm-export wrappers around the real general
//! form, `precision::fixed::{mul, add, sub, sqr, escape_sample}` at the explicit
//! `L in {2, 4, 6, 8}` instantiations (the tiers the adaptive mandelbrot
//! escape kernel selects among). Per-STATIC-limb wrappers exist because
//! `Limbs<L>` is an HList struct, not an array, so a runtime limb INDEX cannot
//! select a field (same convention as `precision_field_bn254fr_oracle_ingot`).
//!
//! GENERATED by crates/codegen/tests/fixtures/precision_fixed_oracle_ingot/gen_fixed_gate.py
//! (regenerate, do not hand-edit). The Rust oracle
//! `crates/codegen/tests/precision_fixed_oracle.rs` compiles this to wasm, runs
//! it under wasmtime, and compares every arithmetic export LIMB-FOR-LIMB plus
//! each escape count/magnitude against an independent num-bigint reference.

use precision::fixed::{mul, add, sub, sqr, escape_sample}
use precision::field::{Limbs, LimbLast, LimbMore}
'''


def limb_access(var, k, l):
    """Field path selecting limb k (0-indexed) of an L-limb HList."""
    path = var
    path += ".tail" * k
    path += ".value" if k == l - 1 else ".lead"
    return path


def build_body(l):
    """The nested LimbMore/LimbLast constructor for build{l}."""
    inner = "LimbLast { value: x%d }" % (l - 1)
    for k in range(l - 2, -1, -1):
        inner = "LimbMore { lead: x%d, tail: %s }" % (k, inner)
    return inner


def build_fn(l):
    params = ", ".join("_ x%d: u32" % k for k in range(l))
    return "fn build%d(%s) -> Limbs<%d> {\n    %s\n}" % (l, params, l, build_body(l))


def bin_params(l):
    """Parameter list for a two-operand op: sa, a0..a_{L-1}, sb, b0..b_{L-1}."""
    parts = ["sa: u32"]
    parts += ["a%d: u32" % k for k in range(l)]
    parts.append("sb: u32")
    parts += ["b%d: u32" % k for k in range(l)]
    return ", ".join(parts)


def un_params(l):
    """Parameter list for a one-operand op (sqr): sa, a0..a_{L-1}."""
    parts = ["sa: u32"]
    parts += ["a%d: u32" % k for k in range(l)]
    return ", ".join(parts)


def build_call(prefix, l):
    return "build%d(%s)" % (l, ", ".join("%s%d" % (prefix, k) for k in range(l)))


def binop_block(op, gen, l):
    """mul/add/sub: sign + one function per limb.

    `gen` is the generic-argument spelling: mul uses <L>, add/sub use <Limbs<L>>.
    """
    lines = []
    call = "%s%s(sa, %s, sb, %s)" % (op, gen, build_call("a", l), build_call("b", l))
    lines.append("pub fn fixed_%s_l%d_sign(%s) -> u32 {" % (op, l, bin_params(l)))
    lines.append("    let (s, _m) = %s" % call)
    lines.append("    s")
    lines.append("}")
    for k in range(l):
        lines.append("pub fn fixed_%s_l%d_limb%d(%s) -> u32 {" % (op, l, k, bin_params(l)))
        lines.append("    let (_s, m) = %s" % call)
        lines.append("    %s" % limb_access("m", k, l))
        lines.append("}")
    return "\n".join(lines)


def sqr_block(l):
    lines = []
    call = "sqr<%d>(sa, %s)" % (l, build_call("a", l))
    lines.append("pub fn fixed_sqr_l%d_sign(%s) -> u32 {" % (l, un_params(l)))
    lines.append("    let (s, _m) = %s" % call)
    lines.append("    s")
    lines.append("}")
    for k in range(l):
        lines.append("pub fn fixed_sqr_l%d_limb%d(%s) -> u32 {" % (l, k, un_params(l)))
        lines.append("    let (_s, m) = %s" % call)
        lines.append("    %s" % limb_access("m", k, l))
        lines.append("}")
    return "\n".join(lines)


def escape_block(l):
    params = ["cxs: u32"]
    params += ["cx%d: u32" % k for k in range(l)]
    params.append("cys: u32")
    params += ["cy%d: u32" % k for k in range(l)]
    params.append("max_iter: i32")
    sig = ", ".join(params)
    sample_call = "escape_sample<%d>(cxs, %s, cys, %s, max_iter)" % (
        l, build_call("cx", l), build_call("cy", l))
    return (
        "pub fn fixed_escape_sample_l%d(%s) -> (i32, f32) {\n"
        "    let sample = %s\n"
        "    (sample.iterations, sample.magnitude_squared)\n}"
    ) % (l, sig, sample_call)


def section(l):
    blocks = [
        "// ---- L = %d ----" % l,
        build_fn(l),
        "",
        binop_block("mul", "<%d>" % l, l),
        "",
        binop_block("add", "<Limbs<%d>>" % l, l),
        "",
        binop_block("sub", "<Limbs<%d>>" % l, l),
        "",
        sqr_block(l),
        "",
        escape_block(l),
    ]
    return "\n".join(blocks)


def main():
    out = [HEADER]
    for l in LS:
        out.append(section(l))
        out.append("")  # trailing blank between sections
    text = "\n".join(out).rstrip("\n") + "\n"
    import sys
    sys.stdout.write(text)


if __name__ == "__main__":
    main()
