[ingot]
name = "mandelbrot_proof_recursive_verifier_air_baby_bear"
version = "0.1.0"

[dependencies]
mandelbrot_proof_fixed_air_receipt_baby_bear = "../fixed-air-receipt-baby-bear"
mandelbrot_proof_fixed_air_baby_bear = "../fixed-air-baby-bear"
mandelbrot_proof_recursive_baby_bear = "../recursive-baby-bear"
merkle_core = "../../../../ingots/merkle_core"
merkle_browser = "../../../../ingots/merkle_browser"
poseidon_baby_bear = "../../../../ingots/poseidon_baby_bear"
precision = "../../../sketches/precision"
quadratic_plan = "../../../../ingots/quadratic_plan"
